import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(body: ListView(children: [Applyer()])),
    );
  }
}

class Applyer extends StatelessWidget {
  const Applyer({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 428,
          height: 926,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: -8,
                top: 322,
                child: Container(
                  width: 436,
                  height: 604,
                  decoration: BoxDecoration(color: const Color(0xFFF0F0F0)),
                ),
              ),
              Positioned(
                left: 174,
                top: 165,
                child: SizedBox(
                  width: 228.96,
                  child: Text(
                    'Di Cari! Kasir dan Pegawai Mini Market',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 15,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      height: 1.20,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 174,
                top: 217,
                child: SizedBox(
                  width: 239,
                  child: Text(
                    'Pria dan Wanita, Part-time, diutamakan yang memiliki pengalaman dalam menangani.',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 9.27,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w300,
                      height: 1.51,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 20,
                top: 155,
                child: Container(
                  width: 141,
                  height: 141,
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF676D74),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(9),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: -2,
                        top: -19,
                        child: Container(
                          width: 144,
                          height: 180,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage(
                                "https://placehold.co/144x180",
                              ),
                              fit: BoxFit.cover,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 17.30,
                child: SizedBox(
                  width: 428,
                  height: 74.67,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 389.33,
                        top: 17.33,
                        child: Opacity(
                          opacity: 0.35,
                          child: Container(
                            width: 22,
                            height: 11.33,
                            decoration: ShapeDecoration(
                              shape: RoundedRectangleBorder(
                                side: BorderSide(width: 1),
                                borderRadius: BorderRadius.circular(2.67),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 391.33,
                        top: 19.33,
                        child: Container(
                          width: 18,
                          height: 7.33,
                          decoration: ShapeDecoration(
                            color: Colors.black,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(1.33),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 21,
                        top: 7.33,
                        child: SizedBox(
                          width: 54,
                          height: 21,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 7,
                                child: SizedBox(
                                  width: 54,
                                  child: Text(
                                    '9:41',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 15,
                                      fontFamily: 'SF Pro Text',
                                      fontWeight: FontWeight.w600,
                                      letterSpacing: -0.30,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 151,
                top: 46.30,
                child: SizedBox(
                  width: 135,
                  height: 73,
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 8,
                    children: [
                      SizedBox(
                        width: 341,
                        child: Text(
                          'Job Requester',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: const Color(0xFF3B3936),
                            fontSize: 24,
                            fontFamily: 'Rubik',
                            fontWeight: FontWeight.w500,
                            height: 1.33,
                            letterSpacing: -0.50,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 21,
                top: 69,
                child: Container(
                  height: 28,
                  padding: const EdgeInsets.all(10),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 10,
                    children: [
                      Container(
                        width: 24,
                        height: 24,
                        clipBehavior: Clip.antiAlias,
                        decoration: BoxDecoration(),
                        child: Stack(),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 18,
                top: 353,
                child: Container(
                  width: 388,
                  height: 61,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(4),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 88,
                top: 366,
                child: SizedBox(
                  width: 228.96,
                  child: Text(
                    'Jane Doe',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 15,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      height: 1.20,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 88,
                top: 384,
                child: SizedBox(
                  width: 228.96,
                  child: Text(
                    '@JaneDoe',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 9.27,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                      height: 1.94,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 26,
                top: 359,
                child: Container(
                  width: 50,
                  height: 50,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/50x50"),
                      fit: BoxFit.cover,
                    ),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 18,
                top: 426,
                child: Container(
                  width: 388,
                  height: 61,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(4),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 88,
                top: 457,
                child: SizedBox(
                  width: 228.96,
                  child: Text(
                    '@Faisalll',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 9.27,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                      height: 1.94,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 26,
                top: 433,
                child: Container(
                  width: 47,
                  height: 47,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/47x47"),
                      fit: BoxFit.cover,
                    ),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 88,
                top: 439,
                child: Text(
                  'Faisal Wijaya',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 15,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                    height: 1.20,
                  ),
                ),
              ),
              Positioned(
                left: 18,
                top: 499,
                child: Container(
                  width: 388,
                  height: 61,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(4),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 88,
                top: 530,
                child: SizedBox(
                  width: 228.96,
                  child: Text(
                    '@AyuyuLes',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 9.27,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                      height: 1.94,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 26,
                top: 506,
                child: Container(
                  width: 47,
                  height: 47,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/47x47"),
                      fit: BoxFit.cover,
                    ),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 88,
                top: 512,
                child: Text(
                  'Ayu Lestari',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 15,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                    height: 1.20,
                  ),
                ),
              ),
              Positioned(
                left: 18,
                top: 572,
                child: Container(
                  width: 388,
                  height: 61,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(4),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 88,
                top: 603,
                child: SizedBox(
                  width: 228.96,
                  child: Text(
                    '@Seungleewife',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 9.27,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                      height: 1.94,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 26,
                top: 579,
                child: Container(
                  width: 47,
                  height: 47,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/47x47"),
                      fit: BoxFit.cover,
                    ),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 88,
                top: 585,
                child: Text(
                  'Siti Aminah',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 15,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                    height: 1.20,
                  ),
                ),
              ),
              Positioned(
                left: 18,
                top: 645,
                child: Container(
                  width: 388,
                  height: 61,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(4),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 88,
                top: 676,
                child: SizedBox(
                  width: 228.96,
                  child: Text(
                    '@proweebss',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 9.27,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                      height: 1.94,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 26,
                top: 652,
                child: Container(
                  width: 47,
                  height: 47,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/47x47"),
                      fit: BoxFit.cover,
                    ),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 88,
                top: 658,
                child: Text(
                  'Bayu Anggara',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 15,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                    height: 1.20,
                  ),
                ),
              ),
              Positioned(
                left: 18,
                top: 718,
                child: Container(
                  width: 388,
                  height: 61,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(4),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 88,
                top: 749,
                child: SizedBox(
                  width: 228.96,
                  child: Text(
                    '@Kyyyy',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 9.27,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                      height: 1.94,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 26,
                top: 725,
                child: Container(
                  width: 47,
                  height: 47,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/47x47"),
                      fit: BoxFit.cover,
                    ),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 88,
                top: 731,
                child: Text(
                  'Rizky Pratama',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 15,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                    height: 1.20,
                  ),
                ),
              ),
              Positioned(
                left: 18,
                top: 791,
                child: Container(
                  width: 388,
                  height: 61,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(4),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 88,
                top: 822,
                child: SizedBox(
                  width: 228.96,
                  child: Text(
                    '@rii.sariii',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 9.27,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                      height: 1.94,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 26,
                top: 798,
                child: Container(
                  width: 47,
                  height: 47,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/47x47"),
                      fit: BoxFit.cover,
                    ),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 88,
                top: 804,
                child: Text(
                  'Kartika Sari',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 15,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                    height: 1.20,
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
