import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(body: ListView(children: [ApplyPekerjaan()])),
    );
  }
}

class ApplyPekerjaan extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 428,
          height: 926,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: Colors.white,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
            shadows: [
              BoxShadow(
                color: Color(0x51000000),
                blurRadius: 24,
                offset: Offset(8, 12),
                spreadRadius: 0,
              ),
            ],
          ),
          child: Stack(
            children: [
              Positioned(
                left: -3,
                top: 0,
                child: Container(
                  width: 429,
                  height: 44,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: -3,
                top: 0,
                child: Container(
                  width: 429,
                  height: 44,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 283,
                top: 44,
                child: Container(
                  padding: const EdgeInsets.all(11),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    spacing: 10,
                    children: [
                      Container(width: 30, height: 30, child: Stack()),
                      Container(
                        width: 12,
                        height: 12,
                        decoration: ShapeDecoration(
                          color: Colors.white,
                          shape: OvalBorder(),
                        ),
                      ),
                      Container(
                        transform:
                            Matrix4.identity()
                              ..translate(0.0, 0.0)
                              ..rotateZ(-1.57),
                        height: 12,
                        decoration: ShapeDecoration(
                          gradient: LinearGradient(
                            begin: Alignment(0.26, 0.29),
                            end: Alignment(1.07, 1.07),
                            colors: [
                              const Color(0xFF091114),
                              const Color(0xC5404379),
                              const Color(0xBF9670F6),
                              const Color(0xBF91B2D4),
                              const Color(0xFFDEF984),
                            ],
                          ),
                          shape: OvalBorder(),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 368,
                top: 56,
                child: Container(
                  width: 25,
                  height: 24,
                  child: Stack(
                    children: [
                      Container(
                        width: 24,
                        height: 24,
                        decoration: ShapeDecoration(
                          color: const Color(0xFFC2C8D5),
                          shape: OvalBorder(),
                        ),
                      ),
                      Positioned(
                        left: 16,
                        top: 0,
                        child: Container(
                          width: 8,
                          height: 8,
                          decoration: ShapeDecoration(
                            color: const Color(0xFF36C782),
                            shape: OvalBorder(
                              side: BorderSide(
                                width: 2,
                                strokeAlign: BorderSide.strokeAlignOutside,
                                color: Colors.white,
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 68,
                top: 331,
                child: Container(
                  width: 277,
                  height: 44,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFF4285F4),
                      ),
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 303,
                top: 339,
                child: Container(
                  width: 30.50,
                  height: 30.50,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 68,
                top: 500,
                child: Container(
                  width: 277,
                  height: 44,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFF4285F4),
                      ),
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 303,
                top: 508,
                child: Container(
                  width: 30.50,
                  height: 30.50,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 127,
                top: 345,
                child: Text(
                  'Upload Resume Saya',
                  style: TextStyle(
                    color: const Color(0xFF726969),
                    fontSize: 12,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                    letterSpacing: 0.60,
                  ),
                ),
              ),
              Positioned(
                left: 76,
                top: 473,
                child: Text(
                  'Nomer Hp',
                  style: TextStyle(
                    color: const Color(0xFF726969),
                    fontSize: 12,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                    letterSpacing: 0.60,
                  ),
                ),
              ),
              Positioned(
                left: 68,
                top: 384,
                child: Text(
                  'Upload File in PDF max 5MB.                   ',
                  style: TextStyle(
                    color: const Color(0xFF726969),
                    fontSize: 12,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                    letterSpacing: 0.60,
                  ),
                ),
              ),
              Positioned(
                left: 71,
                top: 609,
                child: SizedBox(
                  width: 318,
                  child: Text(
                    'Tell us why you want to apply this job',
                    style: TextStyle(
                      color: const Color(0xFF726969),
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                      letterSpacing: 0.60,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 60,
                top: 654,
                child: Container(
                  width: 298,
                  height: 132,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(color: const Color(0xFFB4E2FF)),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 15,
                        top: 10,
                        child: Text(
                          'Tell us more about you',
                          style: TextStyle(
                            color: const Color(0xFF726969),
                            fontSize: 12,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w400,
                            letterSpacing: 0.60,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 49,
                top: 819,
                child: Container(
                  width: 325,
                  padding: const EdgeInsets.all(10),
                  decoration: ShapeDecoration(
                    color: const Color(0xFF4280EF),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(35),
                    ),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 10,
                    children: [
                      Text(
                        'Apply ',
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 20,
                          fontFamily: 'Poppins',
                          fontWeight: FontWeight.w600,
                          letterSpacing: 1.60,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 87,
                top: 283,
                child: SizedBox(
                  width: 104,
                  height: 33,
                  child: Text(
                    'Resume',
                    style: TextStyle(
                      color: Colors.black.withValues(alpha: 229),
                      fontSize: 20,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      letterSpacing: 1.60,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 78,
                top: 440,
                child: SizedBox(
                  width: 104,
                  height: 33,
                  child: Text(
                    'contact',
                    style: TextStyle(
                      color: Colors.black.withValues(alpha: 229),
                      fontSize: 20,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      letterSpacing: 1.60,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 78,
                top: 506,
                child: SizedBox(
                  width: 164,
                  height: 33,
                  child: Text(
                    '08817117233',
                    style: TextStyle(
                      color: Colors.black.withValues(alpha: 229),
                      fontSize: 20,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      letterSpacing: 1.60,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 78,
                top: 576,
                child: SizedBox(
                  width: 313,
                  height: 33,
                  child: Text(
                    'Apply letter (Optional)',
                    style: TextStyle(
                      color: Colors.black.withValues(alpha: 229),
                      fontSize: 20,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      letterSpacing: 1.60,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 42,
                top: 278,
                child: Container(
                  width: 45,
                  height: 43,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 49,
                top: 444,
                child: Container(
                  width: 22.83,
                  height: 25.09,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
