import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(body: ListView(children: [CheckOut()])),
    );
  }
}

class CheckOut extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 428,
          height: 926,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: -1,
                top: 119,
                child: Container(
                  width: 464,
                  height: 775,
                  decoration: BoxDecoration(color: const Color(0xFFF7F7F7)),
                ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  decoration: BoxDecoration(color: Colors.white),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 8,
                    children: [
                      Container(
                        width: 428,
                        height: 59,
                        padding: const EdgeInsets.symmetric(
                          horizontal: 20,
                          vertical: 12,
                        ),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          spacing: 155,
                          children: [
                            Container(
                              width: 82,
                              height: double.infinity,
                              child: Column(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.center,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                spacing: 10,
                                children: [
                                  Container(
                                    width: 376,
                                    height: 50,
                                    decoration: BoxDecoration(
                                      color: Colors.white,
                                    ),
                                  ),
                                  Container(
                                    width: 35,
                                    height: 27,
                                    decoration: BoxDecoration(
                                      color: Colors.black,
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            Container(
                              width: 102,
                              height: double.infinity,
                              padding: const EdgeInsets.only(right: 3),
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.center,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                spacing: 10,
                                children: [
                                  Container(
                                    width: 76,
                                    height: 14,
                                    clipBehavior: Clip.antiAlias,
                                    decoration: BoxDecoration(),
                                    child: Stack(),
                                  ),
                                  Container(
                                    width: 376,
                                    height: 50,
                                    decoration: BoxDecoration(
                                      color: Colors.white,
                                    ),
                                  ),
                                  Container(
                                    width: 79,
                                    height: 27,
                                    decoration: BoxDecoration(
                                      color: Colors.black,
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                      Container(
                        width: 388,
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          spacing: 192,
                          children: [
                            Container(
                              transform:
                                  Matrix4.identity()
                                    ..translate(0.0, 0.0)
                                    ..rotateZ(3.14),
                              width: 24,
                              height: 24,
                              clipBehavior: Clip.antiAlias,
                              decoration: BoxDecoration(),
                              child: Stack(),
                            ),
                            Text(
                              'Check Out',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                color: const Color(0xFF676D74),
                                fontSize: 24.55,
                                fontFamily: 'Hind',
                                fontWeight: FontWeight.w600,
                                height: 1.20,
                              ),
                            ),
                            Row(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.center,
                              spacing: 4,
                              children: [
                                Container(
                                  padding: const EdgeInsets.all(11),
                                  child: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment:
                                        CrossAxisAlignment.start,
                                    spacing: 10,
                                    children: [
                                      Container(
                                        width: 30,
                                        height: 30,
                                        child: Stack(),
                                      ),
                                    ],
                                  ),
                                ),
                                Container(
                                  padding: const EdgeInsets.all(11),
                                  child: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment:
                                        CrossAxisAlignment.start,
                                    spacing: 10,
                                    children: [
                                      Container(
                                        width: 30,
                                        height: 30,
                                        child: Stack(),
                                      ),
                                      Container(
                                        width: 12,
                                        height: 12,
                                        decoration: ShapeDecoration(
                                          color: Colors.white,
                                          shape: OvalBorder(),
                                        ),
                                      ),
                                      Container(
                                        transform:
                                            Matrix4.identity()
                                              ..translate(0.0, 0.0)
                                              ..rotateZ(-1.57),
                                        height: 12,
                                        decoration: ShapeDecoration(
                                          gradient: LinearGradient(
                                            begin: Alignment(0.26, 0.29),
                                            end: Alignment(1.07, 1.07),
                                            colors: [
                                              const Color(0xFF091114),
                                              const Color(0xC5404379),
                                              const Color(0xBF9670F6),
                                              const Color(0xBF91B2D4),
                                              const Color(0xFFDEF984),
                                            ],
                                          ),
                                          shape: OvalBorder(),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ],
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 326,
                top: 223,
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.center,
                  crossAxisAlignment: CrossAxisAlignment.end,
                  spacing: 6,
                  children: [
                    Text(
                      '\$399',
                      style: TextStyle(
                        color: const Color(0xFF333333),
                        fontSize: 22,
                        fontFamily: 'Hind',
                        fontWeight: FontWeight.w600,
                        height: 1.14,
                      ),
                    ),
                    Text(
                      '\$599',
                      style: TextStyle(
                        color: const Color(0xFF6B6B6B),
                        fontSize: 14,
                        fontFamily: 'Hind',
                        fontWeight: FontWeight.w400,
                        textDecoration: TextDecoration.lineThrough,
                      ),
                    ),
                  ],
                ),
              ),
              Positioned(
                left: 172,
                top: 167,
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  spacing: 10,
                  children: [
                    Text(
                      'Nail Art',
                      style: TextStyle(
                        color: const Color(0xFF333333),
                        fontSize: 24.55,
                        fontFamily: 'Hind',
                        fontWeight: FontWeight.w600,
                        height: 1.02,
                      ),
                    ),
                  ],
                ),
              ),
              Positioned(
                left: 172,
                top: 192,
                child: Text(
                  'French Tips',
                  style: TextStyle(
                    color: const Color(0xFF676D74),
                    fontSize: 15.41,
                    fontFamily: 'Hind',
                    fontWeight: FontWeight.w400,
                    height: 1.62,
                  ),
                ),
              ),
              Positioned(
                left: 172,
                top: 220,
                child: Text(
                  'Total',
                  style: TextStyle(
                    color: const Color(0xFF676D74),
                    fontSize: 15.41,
                    fontFamily: 'Hind',
                    fontWeight: FontWeight.w400,
                    height: 1.62,
                  ),
                ),
              ),
              Positioned(
                left: 384,
                top: 192,
                child: Text(
                  'x 1',
                  style: TextStyle(
                    color: const Color(0xFF676D74),
                    fontSize: 15.41,
                    fontFamily: 'Hind',
                    fontWeight: FontWeight.w400,
                    height: 1.62,
                  ),
                ),
              ),
              Positioned(
                left: 31,
                top: 301,
                child: Text(
                  'Booking',
                  style: TextStyle(
                    color: const Color(0xFF333333),
                    fontSize: 24.55,
                    fontFamily: 'Hind',
                    fontWeight: FontWeight.w600,
                    height: 1.02,
                  ),
                ),
              ),
              Positioned(
                left: 32,
                top: 528,
                child: Text(
                  'Payment Method',
                  style: TextStyle(
                    color: const Color(0xFF333333),
                    fontSize: 24.55,
                    fontFamily: 'Hind',
                    fontWeight: FontWeight.w600,
                    height: 1.02,
                  ),
                ),
              ),
              Positioned(
                left: 48,
                top: 354,
                child: Text(
                  'Name',
                  style: TextStyle(
                    color: const Color(0xFF676D74),
                    fontSize: 15.41,
                    fontFamily: 'Hind',
                    fontWeight: FontWeight.w400,
                    height: 1.62,
                  ),
                ),
              ),
              Positioned(
                left: 48,
                top: 383,
                child: Text(
                  'Date',
                  style: TextStyle(
                    color: const Color(0xFF676D74),
                    fontSize: 15.41,
                    fontFamily: 'Hind',
                    fontWeight: FontWeight.w400,
                    height: 1.62,
                  ),
                ),
              ),
              Positioned(
                left: 48,
                top: 412,
                child: Text(
                  'Time',
                  style: TextStyle(
                    color: const Color(0xFF676D74),
                    fontSize: 15.41,
                    fontFamily: 'Hind',
                    fontWeight: FontWeight.w400,
                    height: 1.62,
                  ),
                ),
              ),
              Positioned(
                left: 48,
                top: 440,
                child: Text(
                  'Notes',
                  style: TextStyle(
                    color: const Color(0xFF676D74),
                    fontSize: 15.41,
                    fontFamily: 'Hind',
                    fontWeight: FontWeight.w400,
                    height: 1.62,
                  ),
                ),
              ),
              Positioned(
                left: 131,
                top: 354,
                child: Text(
                  ': Jane Doe',
                  style: TextStyle(
                    color: const Color(0xFF676D74),
                    fontSize: 15.41,
                    fontFamily: 'Hind',
                    fontWeight: FontWeight.w400,
                    height: 1.62,
                  ),
                ),
              ),
              Positioned(
                left: 2,
                top: 749,
                child: Container(
                  width: 428,
                  height: 118,
                  decoration: BoxDecoration(
                    color: Colors.white,
                    boxShadow: [
                      BoxShadow(
                        color: Color(0x11000000),
                        blurRadius: 4,
                        offset: Offset(0, -2),
                        spreadRadius: 0,
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 131,
                top: 383,
                child: Text(
                  ': 21',
                  style: TextStyle(
                    color: const Color(0xFF676D74),
                    fontSize: 15.41,
                    fontFamily: 'Hind',
                    fontWeight: FontWeight.w400,
                    height: 1.62,
                  ),
                ),
              ),
              Positioned(
                left: 161,
                top: 383,
                child: Text(
                  'January',
                  style: TextStyle(
                    color: const Color(0xFF676D74),
                    fontSize: 15.41,
                    fontFamily: 'Hind',
                    fontWeight: FontWeight.w400,
                    height: 1.62,
                  ),
                ),
              ),
              Positioned(
                left: 224,
                top: 383,
                child: Text(
                  '2025',
                  style: TextStyle(
                    color: const Color(0xFF676D74),
                    fontSize: 15.41,
                    fontFamily: 'Hind',
                    fontWeight: FontWeight.w400,
                    height: 1.62,
                  ),
                ),
              ),
              Positioned(
                left: 31,
                top: 786,
                child: Container(
                  width: 370,
                  height: 47,
                  padding: const EdgeInsets.all(10),
                  decoration: ShapeDecoration(
                    color: const Color(0xFF827BEB),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(29),
                    ),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 10,
                    children: [
                      Text(
                        'Check Out',
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 21.02,
                          fontFamily: 'Hind',
                          fontWeight: FontWeight.w600,
                          height: 0.76,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 131,
                top: 412,
                child: Text(
                  ': 16 . 30',
                  style: TextStyle(
                    color: const Color(0xFF676D74),
                    fontSize: 15.41,
                    fontFamily: 'Hind',
                    fontWeight: FontWeight.w400,
                    height: 1.62,
                  ),
                ),
              ),
              Positioned(
                left: 131,
                top: 441,
                child: Text(
                  ': Please bring a glitter',
                  style: TextStyle(
                    color: const Color(0xFF676D74),
                    fontSize: 15.41,
                    fontFamily: 'Hind',
                    fontWeight: FontWeight.w400,
                    height: 1.62,
                  ),
                ),
              ),
              Positioned(
                left: 32,
                top: 282,
                child: Container(
                  width: 372,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: const Color(0x30676D74),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 31,
                top: 507,
                child: Container(
                  width: 372,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: const Color(0x30676D74),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 32,
                top: 567,
                child: Container(
                  width: 360,
                  height: 42,
                  decoration: BoxDecoration(color: const Color(0xFFE8E8E8)),
                ),
              ),
              Positioned(
                left: 104,
                top: 575,
                child: SizedBox(
                  width: 38,
                  height: 25,
                  child: Text(
                    'Cash',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 15.41,
                      fontFamily: 'Hind',
                      fontWeight: FontWeight.w600,
                      height: 1.62,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 365,
                top: 580,
                child: Container(
                  width: 15,
                  height: 15,
                  decoration: ShapeDecoration(
                    shape: OvalBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: const Color(0xFF888686),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 368,
                top: 583,
                child: Container(
                  width: 9,
                  height: 9,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF888686),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 32,
                top: 623,
                child: Container(
                  width: 360,
                  height: 42,
                  decoration: BoxDecoration(color: const Color(0xFFF2F2F2)),
                ),
              ),
              Positioned(
                left: 104,
                top: 633,
                child: Text(
                  'Qris',
                  style: TextStyle(
                    color: const Color(0xFF676D74),
                    fontSize: 15.41,
                    fontFamily: 'Hind',
                    fontWeight: FontWeight.w600,
                    height: 1.62,
                  ),
                ),
              ),
              Positioned(
                left: 365,
                top: 636,
                child: Container(
                  width: 15,
                  height: 15,
                  decoration: ShapeDecoration(
                    shape: OvalBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: const Color(0xFFB9B9B9),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 32,
                top: 679,
                child: Container(
                  width: 360,
                  height: 42,
                  decoration: BoxDecoration(color: const Color(0xFFF2F2F2)),
                ),
              ),
              Positioned(
                left: 53,
                top: 691,
                child: Container(
                  width: 17,
                  height: 17,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 104,
                top: 689,
                child: Text(
                  'M-Bank',
                  style: TextStyle(
                    color: const Color(0xFF676D74),
                    fontSize: 15.41,
                    fontFamily: 'Hind',
                    fontWeight: FontWeight.w600,
                    height: 1.62,
                  ),
                ),
              ),
              Positioned(
                left: 365,
                top: 694,
                child: Container(
                  width: 15,
                  height: 15,
                  decoration: ShapeDecoration(
                    shape: OvalBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: const Color(0xFFB9B9B9),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 852,
                child: Container(
                  width: 428,
                  padding: const EdgeInsets.only(top: 12, left: 12, right: 12),
                  decoration: BoxDecoration(color: Colors.white),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Expanded(
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          spacing: 6,
                          children: [
                            Container(
                              width: 24,
                              height: 24,
                              child: Stack(
                                children: [
                                  Positioned(
                                    left: -24.90,
                                    top: 0,
                                    child: Container(
                                      width: 73.80,
                                      height: 24,
                                      child: Column(
                                        mainAxisSize: MainAxisSize.min,
                                        mainAxisAlignment:
                                            MainAxisAlignment.start,
                                        crossAxisAlignment:
                                            CrossAxisAlignment.center,
                                        spacing: 6,
                                        children: [
                                          Container(
                                            width: 24,
                                            height: 24,
                                            clipBehavior: Clip.antiAlias,
                                            decoration: BoxDecoration(),
                                            child: Stack(),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            Text(
                              'Home',
                              style: TextStyle(
                                fontSize: 12,
                                fontFamily: 'Hind',
                                fontWeight: FontWeight.w500,
                                height: 1.33,
                              ),
                            ),
                          ],
                        ),
                      ),
                      Opacity(
                        opacity: 0.60,
                        child: Expanded(
                          child: Column(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.start,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 7,
                            children: [
                              Container(width: 24, height: 24, child: Stack()),
                              Text(
                                'Explore',
                                style: TextStyle(
                                  color: const Color(0xFF676D74),
                                  fontSize: 12,
                                  fontFamily: 'Poppins',
                                  fontWeight: FontWeight.w400,
                                  height: 1.33,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Opacity(
                        opacity: 0.60,
                        child: Expanded(
                          child: Column(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.start,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 6,
                            children: [
                              Container(width: 24, height: 24, child: Stack()),
                              Opacity(
                                opacity: 0.90,
                                child: Text(
                                  'Chat',
                                  style: TextStyle(
                                    color: const Color(0xFF676D74),
                                    fontSize: 12,
                                    fontFamily: 'Poppins',
                                    fontWeight: FontWeight.w500,
                                    height: 1.33,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Opacity(
                        opacity: 0.60,
                        child: Expanded(
                          child: Column(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.start,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 6,
                            children: [
                              Container(width: 24, height: 24, child: Stack()),
                              Text(
                                'Blog',
                                style: TextStyle(
                                  color: const Color(0xFF676D74),
                                  fontSize: 12,
                                  fontFamily: 'Poppins',
                                  fontWeight: FontWeight.w400,
                                  height: 1.33,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Opacity(
                        opacity: 0.60,
                        child: Expanded(
                          child: Column(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.start,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 6,
                            children: [
                              Container(width: 24, height: 24, child: Stack()),
                              Text(
                                'Account',
                                style: TextStyle(
                                  color: const Color(0xFF676D74),
                                  fontSize: 12,
                                  fontFamily: 'Poppins',
                                  fontWeight: FontWeight.w400,
                                  height: 1.33,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 911,
                child: Container(
                  width: 428,
                  height: 30,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.only(
                        bottomLeft: Radius.circular(20),
                        bottomRight: Radius.circular(20),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 264,
                top: 851,
                child: Container(
                  width: 61.46,
                  height: 4,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/61x4"),
                      fit: BoxFit.none,
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(2),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 139.37,
                top: 928,
                child: Container(
                  width: 148.15,
                  height: 5,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(100),
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
