import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          ConfirmationWaiting(),
        ]),
      ),
    );
  }
}

class ConfirmationWaiting extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 428,
          height: 926,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 428,
                  height: 59,
                  padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 12),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 155,
                    children: [
                      Container(
                        width: 82,
                        height: double.infinity,
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          spacing: 10,
                          children: [
                            Container(
                              width: 376,
                              height: 50,
                              decoration: BoxDecoration(color: Colors.white),
                            ),
                            Container(
                              width: 35,
                              height: 27,
                              decoration: BoxDecoration(color: Colors.black),
                            ),
                          ],
                        ),
                      ),
                      Container(
                        width: 102,
                        height: double.infinity,
                        padding: const EdgeInsets.only(right: 3),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          spacing: 10,
                          children: [
                            Container(
                              width: 76,
                              height: 14,
                              clipBehavior: Clip.antiAlias,
                              decoration: BoxDecoration(),
                              child: Stack(),
                            ),
                            Container(
                              width: 376,
                              height: 50,
                              decoration: BoxDecoration(color: Colors.white),
                            ),
                            Container(
                              width: 79,
                              height: 27,
                              decoration: BoxDecoration(color: Colors.black),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 73,
                top: 116,
                child: Container(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(3.14),
                  width: 48,
                  height: 39,
                  padding: const EdgeInsets.symmetric(horizontal: 7, vertical: 2),
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 10,
                    children: [
                    ,
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 195,
                top: 87,
                child: Text(
                  'Job ',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: const Color(0xFF676D74),
                    fontSize: 24.55,
                    fontFamily: 'Hind',
                    fontWeight: FontWeight.w600,
                    height: 1.20,
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 163,
                child: Text(
                  'Your Job',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 16,
                    fontFamily: 'Hind',
                    fontWeight: FontWeight.w400,
                    height: 1,
                  ),
                ),
              ),
              Positioned(
                left: 150,
                top: 235,
                child: Container(
                  width: 33,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: const Color(0xFF999999),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 253,
                top: 235,
                child: Container(
                  width: 33,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: const Color(0xFF999999),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 99,
                top: 209,
                child: Container(
                  width: 34,
                  height: 34,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 91,
                top: 244,
                child: Text(
                  'Client Request',
                  style: TextStyle(
                    color: const Color(0xFFD0D2D6),
                    fontSize: 10,
                    fontFamily: 'Hind',
                    fontWeight: FontWeight.w400,
                    height: 1.60,
                  ),
                ),
              ),
              Positioned(
                left: 201,
                top: 209,
                child: Container(
                  width: 34,
                  height: 34,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 180,
                top: 244,
                child: SizedBox(
                  width: 76,
                  child: Text(
                    'Job Comfirmation',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFF8A82FD),
                      fontSize: 10,
                      fontFamily: 'Hind',
                      fontWeight: FontWeight.w400,
                      height: 1.60,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 304,
                top: 209,
                child: Container(
                  width: 34,
                  height: 34,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 283,
                top: 244,
                child: SizedBox(
                  width: 76,
                  child: Text(
                    'Working On',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFF5B5B5B),
                      fontSize: 10,
                      fontFamily: 'Hind',
                      fontWeight: FontWeight.w400,
                      height: 1.60,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 25,
                top: 460,
                child: Text(
                  'Job Details',
                  style: TextStyle(
                    color: const Color(0xFF333333),
                    fontSize: 24.55,
                    fontFamily: 'Hind',
                    fontWeight: FontWeight.w600,
                    height: 1.02,
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 836,
                child: Container(
                  width: 428,
                  height: 90,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 1,
                        child: Container(
                          width: 428,
                          height: 89,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 59,
                                child: Container(
                                  width: 428,
                                  height: 30,
                                  decoration: ShapeDecoration(
                                    color: Colors.white,
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.only(
                                        bottomLeft: Radius.circular(20),
                                        bottomRight: Radius.circular(20),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 428,
                                  padding: const EdgeInsets.only(top: 12, left: 12, right: 12),
                                  decoration: BoxDecoration(color: Colors.white),
                                  child: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.center,
                                    crossAxisAlignment: CrossAxisAlignment.center,
                                    children: [
                                      Expanded(
                                        child: Column(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.center,
                                          spacing: 6,
                                          children: [
                                            Container(
                                              width: 24,
                                              height: 24,
                                              child: Stack(
                                                children: [
                                                  Positioned(
                                                    left: -24.90,
                                                    top: 0,
                                                    child: Container(
                                                      width: 73.80,
                                                      height: 24,
                                                      child: Column(
                                                        mainAxisSize: MainAxisSize.min,
                                                        mainAxisAlignment: MainAxisAlignment.start,
                                                        crossAxisAlignment: CrossAxisAlignment.center,
                                                        spacing: 6,
                                                        children: [
                                                          Container(
                                                            width: 24,
                                                            height: 24,
                                                            clipBehavior: Clip.antiAlias,
                                                            decoration: BoxDecoration(),
                                                            child: Stack(),
                                                          ),
                                                        ],
                                                      ),
                                                    ),
                                                  ),
                                                ],
                                              ),
                                            ),
                                            Text(
                                              'Home',
                                              style: TextStyle(
                                                color: const Color(0xFF676D74),
                                                fontSize: 12,
                                                fontFamily: 'Poppins',
                                                fontWeight: FontWeight.w500,
                                                height: 1.33,
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                      Opacity(
                                        opacity: 0.60,
                                        child: Expanded(
                                          child: Column(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.start,
                                            crossAxisAlignment: CrossAxisAlignment.center,
                                            spacing: 7,
                                            children: [
                                              Container(width: 24, height: 24, child: Stack()),
                                              Text(
                                                'Explore',
                                                style: TextStyle(
                                                  color: const Color(0xFF827BEB),
                                                  fontSize: 12,
                                                  fontFamily: 'Poppins',
                                                  fontWeight: FontWeight.w500,
                                                  height: 1.33,
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Opacity(
                                        opacity: 0.60,
                                        child: Expanded(
                                          child: Column(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.start,
                                            crossAxisAlignment: CrossAxisAlignment.center,
                                            spacing: 6,
                                            children: [
                                              Container(width: 24, height: 24, child: Stack()),
                                              Opacity(
                                                opacity: 0.90,
                                                child: Text(
                                                  'Chat',
                                                  style: TextStyle(
                                                    color: const Color(0xFF676D74),
                                                    fontSize: 12,
                                                    fontFamily: 'Poppins',
                                                    fontWeight: FontWeight.w500,
                                                    height: 1.33,
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Opacity(
                                        opacity: 0.60,
                                        child: Expanded(
                                          child: Column(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.start,
                                            crossAxisAlignment: CrossAxisAlignment.center,
                                            spacing: 6,
                                            children: [
                                              Container(width: 24, height: 24, child: Stack()),
                                              Text(
                                                'Blog',
                                                style: TextStyle(
                                                  color: const Color(0xFF676D74),
                                                  fontSize: 12,
                                                  fontFamily: 'Poppins',
                                                  fontWeight: FontWeight.w500,
                                                  height: 1.33,
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Opacity(
                                        opacity: 0.60,
                                        child: Expanded(
                                          child: Column(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.start,
                                            crossAxisAlignment: CrossAxisAlignment.center,
                                            spacing: 6,
                                            children: [
                                              Container(width: 24, height: 24, child: Stack()),
                                              Text(
                                                'Account',
                                                style: TextStyle(
                                                  color: const Color(0xFF676D74),
                                                  fontSize: 12,
                                                  fontFamily: 'Poppins',
                                                  fontWeight: FontWeight.w500,
                                                  height: 1.33,
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 101,
                        top: 0,
                        child: Container(
                          width: 61.46,
                          height: 4,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 61.46,
                                  height: 4,
                                  decoration: ShapeDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage("https://placehold.co/61x4"),
                                      fit: BoxFit.none,
                                    ),
                                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(2)),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 25,
                top: 294,
                child: Container(
                  width: 141,
                  height: 141,
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF676D74),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(9)),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: -2,
                        top: -13,
                        child: Container(width: 144, height: 180),
                      ),
                      Positioned(
                        left: -3,
                        top: -19,
                        child: Container(
                          width: 144.05,
                          height: 192,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://placehold.co/144x192"),
                              fit: BoxFit.cover,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 185,
                top: 371,
                child: SizedBox(
                  width: 217,
                  child: Text(
                    'Les Bahasa mandarin sama aku bla bla bla pokoknya sampe bisa jadi china asli....',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 9.27,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w300,
                      height: 1.51,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 185,
                top: 403,
                child: Text(
                  'see more',
                  style: TextStyle(
                    color: const Color(0xFF4285F4),
                    fontSize: 9.27,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w300,
                    height: 1.62,
                  ),
                ),
              ),
              Positioned(
                left: 185,
                top: 318,
                child: Text(
                  'Rp. 2.000.000',
                  style: TextStyle(
                    color: const Color(0xFF59E359),
                    fontSize: 24.27,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w600,
                    height: 0.74,
                  ),
                ),
              ),
              Positioned(
                left: 185,
                top: 347,
                child: SizedBox(
                  width: 233,
                  child: Text(
                    'Les Bahasa Mandarin',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 15,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      height: 1.20,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 85,
                top: 517,
                child: SizedBox(
                  width: 228.96,
                  child: Text(
                    'Jane Doe',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 15,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      height: 1.20,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 85,
                top: 535,
                child: SizedBox(
                  width: 228.96,
                  child: Text(
                    '@JaneDoe',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 9.27,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                      height: 1.94,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 23,
                top: 510,
                child: Container(
                  width: 50,
                  height: 50,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/50x50"),
                      fit: BoxFit.cover,
                    ),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 298,
                top: 518,
                child: Container(
                  width: 83,
                  height: 33,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFF6F6F6),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFFBAC3CD),
                      ),
                      borderRadius: BorderRadius.circular(6),
                    ),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 10,
                    children: [
                      Text(
                        'Paket 3 Bulan',
                        style: TextStyle(
                          color: const Color(0xFF4C4B4B),
                          fontSize: 12,
                          fontFamily: 'Hind',
                          fontWeight: FontWeight.w400,
                          height: 1.33,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 34,
                top: 717,
                child: Container(
                  width: 359,
                  height: 60,
                  padding: const EdgeInsets.all(10),
                  decoration: ShapeDecoration(
                    color: const Color(0xFF827BEB),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(44),
                    ),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 10,
                    children: [
                      Text(
                        'Start Working',
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 20,
                          fontFamily: 'Hind',
                          fontWeight: FontWeight.w600,
                          height: 0.80,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}