import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(body: ListView(children: [ConfirmationWaiting()])),
    );
  }
}

class ConfirmationWaiting extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 428,
          height: 926,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  decoration: BoxDecoration(color: Colors.white),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 8,
                    children: [
                      Container(
                        width: 428,
                        height: 59,
                        padding: const EdgeInsets.symmetric(
                          horizontal: 20,
                          vertical: 12,
                        ),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          spacing: 155,
                          children: [
                            Container(
                              width: 82,
                              height: double.infinity,
                              child: Column(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.center,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                spacing: 10,
                                children: [
                                  Container(
                                    width: 376,
                                    height: 50,
                                    decoration: BoxDecoration(
                                      color: Colors.white,
                                    ),
                                  ),
                                  Container(
                                    width: 35,
                                    height: 27,
                                    decoration: BoxDecoration(
                                      color: Colors.black,
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            Container(
                              width: 102,
                              height: double.infinity,
                              padding: const EdgeInsets.only(right: 3),
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.center,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                spacing: 10,
                                children: [
                                  Container(
                                    width: 76,
                                    height: 14,
                                    clipBehavior: Clip.antiAlias,
                                    decoration: BoxDecoration(),
                                    child: Stack(),
                                  ),
                                  Container(
                                    width: 376,
                                    height: 50,
                                    decoration: BoxDecoration(
                                      color: Colors.white,
                                    ),
                                  ),
                                  Container(
                                    width: 79,
                                    height: 27,
                                    decoration: BoxDecoration(
                                      color: Colors.black,
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                      Container(
                        width: 388,
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          spacing: 192,
                          children: [
                            Container(
                              transform:
                                  Matrix4.identity()
                                    ..translate(0.0, 0.0)
                                    ..rotateZ(3.14),
                              width: 24,
                              height: 24,
                              clipBehavior: Clip.antiAlias,
                              decoration: BoxDecoration(),
                              child: Stack(),
                            ),
                            Text(
                              'Job Request',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                color: const Color(0xFF676D74),
                                fontSize: 24.55,
                                fontFamily: 'Hind',
                                fontWeight: FontWeight.w600,
                                height: 1.20,
                              ),
                            ),
                            Row(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.center,
                              spacing: 4,
                              children: [
                                Container(
                                  padding: const EdgeInsets.all(11),
                                  child: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment:
                                        CrossAxisAlignment.start,
                                    spacing: 10,
                                    children: [
                                      Container(
                                        width: 30,
                                        height: 30,
                                        child: Stack(),
                                      ),
                                    ],
                                  ),
                                ),
                                Container(
                                  padding: const EdgeInsets.all(11),
                                  child: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment:
                                        CrossAxisAlignment.start,
                                    spacing: 10,
                                    children: [
                                      Container(
                                        width: 30,
                                        height: 30,
                                        child: Stack(),
                                      ),
                                      Container(
                                        width: 12,
                                        height: 12,
                                        decoration: ShapeDecoration(
                                          color: Colors.white,
                                          shape: OvalBorder(),
                                        ),
                                      ),
                                      Container(
                                        transform:
                                            Matrix4.identity()
                                              ..translate(0.0, 0.0)
                                              ..rotateZ(-1.57),
                                        height: 12,
                                        decoration: ShapeDecoration(
                                          gradient: LinearGradient(
                                            begin: Alignment(0.26, 0.29),
                                            end: Alignment(1.07, 1.07),
                                            colors: [
                                              const Color(0xFF091114),
                                              const Color(0xC5404379),
                                              const Color(0xBF9670F6),
                                              const Color(0xBF91B2D4),
                                              const Color(0xFFDEF984),
                                            ],
                                          ),
                                          shape: OvalBorder(),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ],
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 163,
                child: Text(
                  'Your Request',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 16,
                    fontFamily: 'Hind',
                    fontWeight: FontWeight.w400,
                    height: 1,
                  ),
                ),
              ),
              Positioned(
                left: 150,
                top: 235,
                child: Container(
                  width: 33,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: const Color(0xFF999999),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 253,
                top: 235,
                child: Container(
                  width: 33,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: const Color(0xFF999999),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 99,
                top: 209,
                child: Container(
                  width: 34,
                  height: 34,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 91,
                top: 244,
                child: Text(
                  'Requesting',
                  style: TextStyle(
                    color: const Color(0xFFD0D2D6),
                    fontSize: 10,
                    fontFamily: 'Hind',
                    fontWeight: FontWeight.w400,
                    height: 1.60,
                  ),
                ),
              ),
              Positioned(
                left: 201,
                top: 209,
                child: Container(
                  width: 34,
                  height: 34,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 180,
                top: 244,
                child: SizedBox(
                  width: 76,
                  child: Text(
                    'Job Comfirmation',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFF8A82FD),
                      fontSize: 10,
                      fontFamily: 'Hind',
                      fontWeight: FontWeight.w400,
                      height: 1.60,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 304,
                top: 209,
                child: Container(
                  width: 34,
                  height: 34,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 283,
                top: 244,
                child: SizedBox(
                  width: 76,
                  child: Text(
                    'Working On',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFF5B5B5B),
                      fontSize: 10,
                      fontFamily: 'Hind',
                      fontWeight: FontWeight.w400,
                      height: 1.60,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 25,
                top: 308,
                child: Container(
                  width: 130,
                  height: 112,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/130x112"),
                      fit: BoxFit.cover,
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 169,
                top: 361,
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.center,
                  crossAxisAlignment: CrossAxisAlignment.end,
                  spacing: 6,
                  children: [
                    Text(
                      'Rp. 150.000',
                      style: TextStyle(
                        color: const Color(0xFF59E359),
                        fontSize: 24.55,
                        fontFamily: 'Hind',
                        fontWeight: FontWeight.w600,
                        height: 1.02,
                      ),
                    ),
                  ],
                ),
              ),
              Positioned(
                left: 166,
                top: 326,
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  spacing: 10,
                  children: [
                    Text(
                      'Angkat Barang ',
                      style: TextStyle(
                        color: const Color(0xFF333333),
                        fontSize: 24.55,
                        fontFamily: 'Hind',
                        fontWeight: FontWeight.w600,
                        height: 1.02,
                      ),
                    ),
                  ],
                ),
              ),
              Positioned(
                left: 25,
                top: 460,
                child: Text(
                  'Job Apply',
                  style: TextStyle(
                    color: const Color(0xFF333333),
                    fontSize: 24.55,
                    fontFamily: 'Hind',
                    fontWeight: FontWeight.w600,
                    height: 1.02,
                  ),
                ),
              ),
              Positioned(
                left: 48,
                top: 495,
                child: Text(
                  'Date  ',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 14,
                    fontFamily: 'Rubik',
                    fontWeight: FontWeight.w400,
                    height: 1.14,
                  ),
                ),
              ),
              Positioned(
                left: 93,
                top: 495,
                child: Text(
                  ': 21 - 05 - 2025',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 14,
                    fontFamily: 'Rubik',
                    fontWeight: FontWeight.w400,
                    height: 1.14,
                  ),
                ),
              ),
              Positioned(
                left: 93,
                top: 519,
                child: Text(
                  ': 19.20 - 20.35',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 14,
                    fontFamily: 'Rubik',
                    fontWeight: FontWeight.w400,
                    height: 1.14,
                  ),
                ),
              ),
              Positioned(
                left: 93,
                top: 543,
                child: Text(
                  ': Tambah Konsumsi',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 14,
                    fontFamily: 'Rubik',
                    fontWeight: FontWeight.w400,
                    height: 1.14,
                  ),
                ),
              ),
              Positioned(
                left: 48,
                top: 519,
                child: Text(
                  'Time ',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 14,
                    fontFamily: 'Rubik',
                    fontWeight: FontWeight.w400,
                    height: 1.14,
                  ),
                ),
              ),
              Positioned(
                left: 48,
                top: 543,
                child: Text(
                  'Notes',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 14,
                    fontFamily: 'Rubik',
                    fontWeight: FontWeight.w400,
                    height: 1.14,
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 836,
                child: Container(
                  width: 428,
                  height: 90,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 1,
                        child: Container(
                          width: 428,
                          height: 89,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 59,
                                child: Container(
                                  width: 428,
                                  height: 30,
                                  decoration: ShapeDecoration(
                                    color: Colors.white,
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.only(
                                        bottomLeft: Radius.circular(20),
                                        bottomRight: Radius.circular(20),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 428,
                                  padding: const EdgeInsets.only(
                                    top: 12,
                                    left: 12,
                                    right: 12,
                                  ),
                                  decoration: BoxDecoration(
                                    color: Colors.white,
                                  ),
                                  child: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.center,
                                    crossAxisAlignment:
                                        CrossAxisAlignment.center,
                                    children: [
                                      Expanded(
                                        child: Column(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment:
                                              MainAxisAlignment.start,
                                          crossAxisAlignment:
                                              CrossAxisAlignment.center,
                                          spacing: 6,
                                          children: [
                                            Container(
                                              width: 24,
                                              height: 24,
                                              child: Stack(
                                                children: [
                                                  Positioned(
                                                    left: -24.90,
                                                    top: 0,
                                                    child: Container(
                                                      width: 73.80,
                                                      height: 24,
                                                      child: Column(
                                                        mainAxisSize:
                                                            MainAxisSize.min,
                                                        mainAxisAlignment:
                                                            MainAxisAlignment
                                                                .start,
                                                        crossAxisAlignment:
                                                            CrossAxisAlignment
                                                                .center,
                                                        spacing: 6,
                                                        children: [
                                                          Container(
                                                            width: 24,
                                                            height: 24,
                                                            clipBehavior:
                                                                Clip.antiAlias,
                                                            decoration:
                                                                BoxDecoration(),
                                                            child: Stack(),
                                                          ),
                                                        ],
                                                      ),
                                                    ),
                                                  ),
                                                ],
                                              ),
                                            ),
                                            Text(
                                              'Home',
                                              style: TextStyle(
                                                color: const Color(0xFF676D74),
                                                fontSize: 12,
                                                fontFamily: 'Poppins',
                                                fontWeight: FontWeight.w500,
                                                height: 1.33,
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                      Opacity(
                                        opacity: 0.60,
                                        child: Expanded(
                                          child: Column(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment:
                                                MainAxisAlignment.start,
                                            crossAxisAlignment:
                                                CrossAxisAlignment.center,
                                            spacing: 7,
                                            children: [
                                              Container(
                                                width: 24,
                                                height: 24,
                                                child: Stack(),
                                              ),
                                              Text(
                                                'Explore',
                                                style: TextStyle(
                                                  color: const Color(
                                                    0xFF827BEB,
                                                  ),
                                                  fontSize: 12,
                                                  fontFamily: 'Poppins',
                                                  fontWeight: FontWeight.w500,
                                                  height: 1.33,
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Opacity(
                                        opacity: 0.60,
                                        child: Expanded(
                                          child: Column(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment:
                                                MainAxisAlignment.start,
                                            crossAxisAlignment:
                                                CrossAxisAlignment.center,
                                            spacing: 6,
                                            children: [
                                              Container(
                                                width: 24,
                                                height: 24,
                                                child: Stack(),
                                              ),
                                              Opacity(
                                                opacity: 0.90,
                                                child: Text(
                                                  'Chat',
                                                  style: TextStyle(
                                                    color: const Color(
                                                      0xFF676D74,
                                                    ),
                                                    fontSize: 12,
                                                    fontFamily: 'Poppins',
                                                    fontWeight: FontWeight.w500,
                                                    height: 1.33,
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Opacity(
                                        opacity: 0.60,
                                        child: Expanded(
                                          child: Column(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment:
                                                MainAxisAlignment.start,
                                            crossAxisAlignment:
                                                CrossAxisAlignment.center,
                                            spacing: 6,
                                            children: [
                                              Container(
                                                width: 24,
                                                height: 24,
                                                child: Stack(),
                                              ),
                                              Text(
                                                'Blog',
                                                style: TextStyle(
                                                  color: const Color(
                                                    0xFF676D74,
                                                  ),
                                                  fontSize: 12,
                                                  fontFamily: 'Poppins',
                                                  fontWeight: FontWeight.w500,
                                                  height: 1.33,
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Opacity(
                                        opacity: 0.60,
                                        child: Expanded(
                                          child: Column(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment:
                                                MainAxisAlignment.start,
                                            crossAxisAlignment:
                                                CrossAxisAlignment.center,
                                            spacing: 6,
                                            children: [
                                              Container(
                                                width: 24,
                                                height: 24,
                                                child: Stack(),
                                              ),
                                              Text(
                                                'Account',
                                                style: TextStyle(
                                                  color: const Color(
                                                    0xFF676D74,
                                                  ),
                                                  fontSize: 12,
                                                  fontFamily: 'Poppins',
                                                  fontWeight: FontWeight.w500,
                                                  height: 1.33,
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 101,
                        top: 0,
                        child: Container(
                          width: 61.46,
                          height: 4,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 61.46,
                                  height: 4,
                                  decoration: ShapeDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage(
                                        "https://placehold.co/61x4",
                                      ),
                                      fit: BoxFit.none,
                                    ),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(2),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
