import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(body: ListView(children: [EditPopup()])),
    );
  }
}

class EditPopup extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 428,
          height: 546,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: Colors.white,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(16),
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: 43,
                top: 130,
                child: Container(
                  width: 342,
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    spacing: 15,
                    children: [
                      SizedBox(
                        width: 251,
                        height: 32,
                        child: Text(
                          'Title ',
                          style: TextStyle(
                            color: const Color(0xFF676D74),
                            fontSize: 12.36,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w500,
                            height: 2.59,
                            letterSpacing: -0.50,
                          ),
                        ),
                      ),
                      Container(
                        width: 342,
                        decoration: ShapeDecoration(
                          shape: RoundedRectangleBorder(
                            side: BorderSide(
                              width: 1,
                              strokeAlign: BorderSide.strokeAlignCenter,
                              color: const Color(0xFFCBCBCB),
                            ),
                          ),
                        ),
                      ),
                      SizedBox(
                        width: 325,
                        height: 21,
                        child: Text(
                          'Angkat Barang',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 20,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w400,
                            letterSpacing: -0.30,
                          ),
                        ),
                      ),
                      SizedBox(
                        width: 251,
                        height: 32,
                        child: Text(
                          'Price',
                          style: TextStyle(
                            color: const Color(0xFF676D74),
                            fontSize: 12.36,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w500,
                            height: 2.59,
                            letterSpacing: -0.50,
                          ),
                        ),
                      ),
                      Container(
                        width: 342,
                        decoration: ShapeDecoration(
                          shape: RoundedRectangleBorder(
                            side: BorderSide(
                              width: 1,
                              strokeAlign: BorderSide.strokeAlignCenter,
                              color: const Color(0xFFCBCBCB),
                            ),
                          ),
                        ),
                      ),
                      SizedBox(
                        width: 325,
                        height: 21,
                        child: Text(
                          'Rp. 150.000',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 20,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w400,
                            letterSpacing: -0.30,
                          ),
                        ),
                      ),
                      SizedBox(
                        width: 251,
                        height: 32,
                        child: Text(
                          'Decs',
                          style: TextStyle(
                            color: const Color(0xFF676D74),
                            fontSize: 12.36,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w500,
                            height: 2.59,
                            letterSpacing: -0.50,
                          ),
                        ),
                      ),
                      Container(
                        width: 341,
                        decoration: ShapeDecoration(
                          shape: RoundedRectangleBorder(
                            side: BorderSide(
                              width: 1,
                              strokeAlign: BorderSide.strokeAlignCenter,
                              color: const Color(0xFFCBCBCB),
                            ),
                          ),
                        ),
                      ),
                      SizedBox(
                        width: 325,
                        height: 51,
                        child: Text(
                          'bantu angkut barang kotakan isi makanan ringan di transmart rungkut surabaya, dibutuhkan 10 orang ',
                          style: TextStyle(
                            color: const Color(0xFF333333),
                            fontSize: 12.36,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w400,
                            height: 1.46,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 19,
                top: 82.50,
                child: Container(
                  width: 389,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: const Color(0xFFCBCBCB),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 34,
                top: 458,
                child: Container(
                  width: 360,
                  height: 60,
                  padding: const EdgeInsets.all(10),
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF4280EF),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(41),
                    ),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 10,
                    children: [
                      Text(
                        'Confirm',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 20,
                          fontFamily: 'Plus Jakarta Sans',
                          fontWeight: FontWeight.w600,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 146,
                top: 42,
                child: Container(
                  width: 135.82,
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 8,
                    children: [
                      SizedBox(
                        width: 341,
                        child: Text(
                          'Edit Request',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: const Color(0xFF3B3936),
                            fontSize: 24,
                            fontFamily: 'Rubik',
                            fontWeight: FontWeight.w500,
                            height: 1.33,
                            letterSpacing: -0.50,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
