import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(body: ListView(children: [Keranjang()])),
    );
  }
}

class Keranjang extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 428,
          height: 926,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 1,
                top: 130,
                child: Container(
                  width: 428,
                  height: 776,
                  decoration: BoxDecoration(color: const Color(0xFFF5F5F5)),
                ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  decoration: BoxDecoration(color: Colors.white),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 8,
                    children: [
                      Container(
                        width: 428,
                        height: 59,
                        padding: const EdgeInsets.symmetric(
                          horizontal: 20,
                          vertical: 12,
                        ),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          spacing: 155,
                          children: [
                            Container(
                              width: 82,
                              height: double.infinity,
                              child: Column(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.center,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                spacing: 10,
                                children: [
                                  Container(
                                    width: 376,
                                    height: 50,
                                    decoration: BoxDecoration(
                                      color: Colors.white,
                                    ),
                                  ),
                                  Container(
                                    width: 35,
                                    height: 27,
                                    decoration: BoxDecoration(
                                      color: Colors.black,
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            Container(
                              width: 102,
                              height: double.infinity,
                              padding: const EdgeInsets.only(right: 3),
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.center,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                spacing: 10,
                                children: [
                                  Container(
                                    width: 76,
                                    height: 14,
                                    clipBehavior: Clip.antiAlias,
                                    decoration: BoxDecoration(),
                                    child: Stack(),
                                  ),
                                  Container(
                                    width: 376,
                                    height: 50,
                                    decoration: BoxDecoration(
                                      color: Colors.white,
                                    ),
                                  ),
                                  Container(
                                    width: 79,
                                    height: 27,
                                    decoration: BoxDecoration(
                                      color: Colors.black,
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                      Container(
                        width: 388,
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          spacing: 192,
                          children: [
                            Container(
                              transform:
                                  Matrix4.identity()
                                    ..translate(0.0, 0.0)
                                    ..rotateZ(3.14),
                              width: 24,
                              height: 24,
                              clipBehavior: Clip.antiAlias,
                              decoration: BoxDecoration(),
                              child: Stack(),
                            ),
                            Text(
                              'Shopping Bag',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                color: const Color(0xFF676D74),
                                fontSize: 24.55,
                                fontFamily: 'Hind',
                                fontWeight: FontWeight.w600,
                                height: 1.20,
                              ),
                            ),
                            Row(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.center,
                              spacing: 4,
                              children: [
                                Container(
                                  padding: const EdgeInsets.all(11),
                                  child: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment:
                                        CrossAxisAlignment.start,
                                    spacing: 10,
                                    children: [
                                      Container(
                                        width: 30,
                                        height: 30,
                                        child: Stack(),
                                      ),
                                    ],
                                  ),
                                ),
                                Container(
                                  padding: const EdgeInsets.all(11),
                                  child: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment:
                                        CrossAxisAlignment.start,
                                    spacing: 10,
                                    children: [
                                      Container(
                                        width: 30,
                                        height: 30,
                                        child: Stack(),
                                      ),
                                      Container(
                                        width: 12,
                                        height: 12,
                                        decoration: ShapeDecoration(
                                          color: Colors.white,
                                          shape: OvalBorder(),
                                        ),
                                      ),
                                      Container(
                                        transform:
                                            Matrix4.identity()
                                              ..translate(0.0, 0.0)
                                              ..rotateZ(-1.57),
                                        height: 12,
                                        decoration: ShapeDecoration(
                                          gradient: LinearGradient(
                                            begin: Alignment(0.26, 0.29),
                                            end: Alignment(1.07, 1.07),
                                            colors: [
                                              const Color(0xFF091114),
                                              const Color(0xC5404379),
                                              const Color(0xBF9670F6),
                                              const Color(0xBF91B2D4),
                                              const Color(0xFFDEF984),
                                            ],
                                          ),
                                          shape: OvalBorder(),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ],
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 130,
                child: Container(
                  width: 429,
                  height: 174,
                  decoration: BoxDecoration(color: const Color(0xFFDFDFDF)),
                ),
              ),
              Positioned(
                left: 186,
                top: 175,
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  spacing: 10,
                  children: [
                    Text(
                      'Nail Art',
                      style: TextStyle(
                        color: const Color(0xFF333333),
                        fontSize: 24.55,
                        fontFamily: 'Hind',
                        fontWeight: FontWeight.w600,
                        height: 1.02,
                      ),
                    ),
                  ],
                ),
              ),
              Positioned(
                left: 186,
                top: 206,
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.center,
                  crossAxisAlignment: CrossAxisAlignment.end,
                  spacing: 6,
                  children: [
                    Text(
                      '\$399',
                      style: TextStyle(
                        color: const Color(0xFF333333),
                        fontSize: 22,
                        fontFamily: 'Hind',
                        fontWeight: FontWeight.w600,
                        height: 1.14,
                      ),
                    ),
                    Text(
                      '\$599',
                      style: TextStyle(
                        color: const Color(0xFF6B6B6B),
                        fontSize: 14,
                        fontFamily: 'Hind',
                        fontWeight: FontWeight.w400,
                        textDecoration: TextDecoration.lineThrough,
                      ),
                    ),
                  ],
                ),
              ),
              Positioned(
                left: 186,
                top: 240,
                child: Container(
                  width: 215,
                  height: 30,
                  padding: const EdgeInsets.all(10),
                  decoration: ShapeDecoration(
                    color: const Color(0xFF827BEB),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(40),
                    ),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 10,
                    children: [
                      Text(
                        'French Tips',
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 15.41,
                          fontFamily: 'Hind',
                          fontWeight: FontWeight.w400,
                          height: 1.62,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 22,
                top: 303.50,
                child: Container(
                  width: 372,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: const Color(0x30676D74),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 186,
                top: 340,
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  spacing: 10,
                  children: [
                    Text(
                      'Nail Art',
                      style: TextStyle(
                        color: const Color(0xFF333333),
                        fontSize: 24.55,
                        fontFamily: 'Hind',
                        fontWeight: FontWeight.w600,
                        height: 1.02,
                      ),
                    ),
                  ],
                ),
              ),
              Positioned(
                left: 186,
                top: 371,
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.center,
                  crossAxisAlignment: CrossAxisAlignment.end,
                  spacing: 6,
                  children: [
                    Text(
                      '\$399',
                      style: TextStyle(
                        color: const Color(0xFF333333),
                        fontSize: 22,
                        fontFamily: 'Hind',
                        fontWeight: FontWeight.w600,
                        height: 1.14,
                      ),
                    ),
                    Text(
                      '\$599',
                      style: TextStyle(
                        color: const Color(0xFF6B6B6B),
                        fontSize: 14,
                        fontFamily: 'Hind',
                        fontWeight: FontWeight.w400,
                        textDecoration: TextDecoration.lineThrough,
                      ),
                    ),
                  ],
                ),
              ),
              Positioned(
                left: 186,
                top: 405,
                child: Container(
                  width: 215,
                  height: 30,
                  padding: const EdgeInsets.all(10),
                  decoration: ShapeDecoration(
                    color: const Color(0xFF827BEB),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(40),
                    ),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 10,
                    children: [
                      Text(
                        'French Tips',
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 15.41,
                          fontFamily: 'Hind',
                          fontWeight: FontWeight.w400,
                          height: 1.62,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 22,
                top: 468.50,
                child: Container(
                  width: 372,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: const Color(0x30676D74),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 186,
                top: 505,
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  spacing: 10,
                  children: [
                    Text(
                      'Nail Art',
                      style: TextStyle(
                        color: const Color(0xFF333333),
                        fontSize: 24.55,
                        fontFamily: 'Hind',
                        fontWeight: FontWeight.w600,
                        height: 1.02,
                      ),
                    ),
                  ],
                ),
              ),
              Positioned(
                left: 186,
                top: 536,
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.center,
                  crossAxisAlignment: CrossAxisAlignment.end,
                  spacing: 6,
                  children: [
                    Text(
                      '\$399',
                      style: TextStyle(
                        color: const Color(0xFF333333),
                        fontSize: 22,
                        fontFamily: 'Hind',
                        fontWeight: FontWeight.w600,
                        height: 1.14,
                      ),
                    ),
                    Text(
                      '\$599',
                      style: TextStyle(
                        color: const Color(0xFF6B6B6B),
                        fontSize: 14,
                        fontFamily: 'Hind',
                        fontWeight: FontWeight.w400,
                        textDecoration: TextDecoration.lineThrough,
                      ),
                    ),
                  ],
                ),
              ),
              Positioned(
                left: 186,
                top: 570,
                child: Container(
                  width: 215,
                  height: 30,
                  padding: const EdgeInsets.all(10),
                  decoration: ShapeDecoration(
                    color: const Color(0xFF827BEB),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(40),
                    ),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 10,
                    children: [
                      Text(
                        'French Tips',
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 15.41,
                          fontFamily: 'Hind',
                          fontWeight: FontWeight.w400,
                          height: 1.62,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 22,
                top: 633.50,
                child: Container(
                  width: 372,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: const Color(0x30676D74),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 186,
                top: 670,
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  spacing: 10,
                  children: [
                    Text(
                      'Nail Art',
                      style: TextStyle(
                        color: const Color(0xFF333333),
                        fontSize: 24.55,
                        fontFamily: 'Hind',
                        fontWeight: FontWeight.w600,
                        height: 1.02,
                      ),
                    ),
                  ],
                ),
              ),
              Positioned(
                left: 186,
                top: 701,
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.center,
                  crossAxisAlignment: CrossAxisAlignment.end,
                  spacing: 6,
                  children: [
                    Text(
                      '\$399',
                      style: TextStyle(
                        color: const Color(0xFF333333),
                        fontSize: 22,
                        fontFamily: 'Hind',
                        fontWeight: FontWeight.w600,
                        height: 1.14,
                      ),
                    ),
                    Text(
                      '\$599',
                      style: TextStyle(
                        color: const Color(0xFF6B6B6B),
                        fontSize: 14,
                        fontFamily: 'Hind',
                        fontWeight: FontWeight.w400,
                        textDecoration: TextDecoration.lineThrough,
                      ),
                    ),
                  ],
                ),
              ),
              Positioned(
                left: 186,
                top: 735,
                child: Container(
                  width: 215,
                  height: 30,
                  padding: const EdgeInsets.all(10),
                  decoration: ShapeDecoration(
                    color: const Color(0xFF827BEB),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(40),
                    ),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 10,
                    children: [
                      Text(
                        'French Tips',
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 15.41,
                          fontFamily: 'Hind',
                          fontWeight: FontWeight.w400,
                          height: 1.62,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 22,
                top: 798.50,
                child: Container(
                  width: 372,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: const Color(0x30676D74),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 695,
                child: Container(
                  width: 428,
                  height: 158,
                  decoration: BoxDecoration(color: Colors.white),
                ),
              ),
              Positioned(
                left: 32,
                top: 794,
                child: Container(
                  width: 365,
                  height: 39,
                  padding: const EdgeInsets.all(10),
                  decoration: ShapeDecoration(
                    color: const Color(0xFF827BEB),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(40),
                    ),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 10,
                    children: [
                      Text(
                        'Booking',
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 21.02,
                          fontFamily: 'Hind',
                          fontWeight: FontWeight.w600,
                          height: 1.19,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 24,
                top: 851.50,
                child: Container(
                  width: 372,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: const Color(0x30676D74),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 317,
                top: 763,
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.center,
                  crossAxisAlignment: CrossAxisAlignment.end,
                  spacing: 6,
                  children: [
                    Text(
                      '\$399',
                      style: TextStyle(
                        color: const Color(0xFF333333),
                        fontSize: 22,
                        fontFamily: 'Hind',
                        fontWeight: FontWeight.w600,
                        height: 1.14,
                      ),
                    ),
                    Text(
                      '\$599',
                      style: TextStyle(
                        color: const Color(0xFF6B6B6B),
                        fontSize: 14,
                        fontFamily: 'Hind',
                        fontWeight: FontWeight.w400,
                        textDecoration: TextDecoration.lineThrough,
                      ),
                    ),
                  ],
                ),
              ),
              Positioned(
                left: 32,
                top: 710,
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  spacing: 10,
                  children: [
                    Text(
                      'Nail Art',
                      style: TextStyle(
                        color: const Color(0xFF333333),
                        fontSize: 24.55,
                        fontFamily: 'Hind',
                        fontWeight: FontWeight.w600,
                        height: 1.02,
                      ),
                    ),
                  ],
                ),
              ),
              Positioned(
                left: 32,
                top: 735,
                child: Text(
                  'French Tips',
                  style: TextStyle(
                    color: const Color(0xFF676D74),
                    fontSize: 15.41,
                    fontFamily: 'Hind',
                    fontWeight: FontWeight.w400,
                    height: 1.62,
                  ),
                ),
              ),
              Positioned(
                left: 32,
                top: 763,
                child: Text(
                  'Total',
                  style: TextStyle(
                    color: const Color(0xFF676D74),
                    fontSize: 15.41,
                    fontFamily: 'Hind',
                    fontWeight: FontWeight.w400,
                    height: 1.62,
                  ),
                ),
              ),
              Positioned(
                left: 375,
                top: 732,
                child: Text(
                  'x 1',
                  style: TextStyle(
                    color: const Color(0xFF676D74),
                    fontSize: 15.41,
                    fontFamily: 'Hind',
                    fontWeight: FontWeight.w400,
                    height: 1.62,
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 852,
                child: Container(
                  width: 428,
                  padding: const EdgeInsets.only(top: 12, left: 12, right: 12),
                  decoration: BoxDecoration(color: Colors.white),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Expanded(
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          spacing: 6,
                          children: [
                            Container(
                              width: 24,
                              height: 24,
                              child: Stack(
                                children: [
                                  Positioned(
                                    left: -24.90,
                                    top: 0,
                                    child: Container(
                                      width: 73.80,
                                      height: 24,
                                      child: Column(
                                        mainAxisSize: MainAxisSize.min,
                                        mainAxisAlignment:
                                            MainAxisAlignment.start,
                                        crossAxisAlignment:
                                            CrossAxisAlignment.center,
                                        spacing: 6,
                                        children: [
                                          Container(
                                            width: 24,
                                            height: 24,
                                            clipBehavior: Clip.antiAlias,
                                            decoration: BoxDecoration(),
                                            child: Stack(),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            Text(
                              'Home',
                              style: TextStyle(
                                fontSize: 12,
                                fontFamily: 'Hind',
                                fontWeight: FontWeight.w500,
                                height: 1.33,
                              ),
                            ),
                          ],
                        ),
                      ),
                      Opacity(
                        opacity: 0.60,
                        child: Expanded(
                          child: Column(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.start,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 7,
                            children: [
                              Container(width: 24, height: 24, child: Stack()),
                              Text(
                                'Explore',
                                style: TextStyle(
                                  color: const Color(0xFF676D74),
                                  fontSize: 12,
                                  fontFamily: 'Poppins',
                                  fontWeight: FontWeight.w400,
                                  height: 1.33,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Opacity(
                        opacity: 0.60,
                        child: Expanded(
                          child: Column(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.start,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 6,
                            children: [
                              Container(width: 24, height: 24, child: Stack()),
                              Opacity(
                                opacity: 0.90,
                                child: Text(
                                  'Chat',
                                  style: TextStyle(
                                    color: const Color(0xFF676D74),
                                    fontSize: 12,
                                    fontFamily: 'Poppins',
                                    fontWeight: FontWeight.w500,
                                    height: 1.33,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Opacity(
                        opacity: 0.60,
                        child: Expanded(
                          child: Column(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.start,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 6,
                            children: [
                              Container(width: 24, height: 24, child: Stack()),
                              Text(
                                'Blog',
                                style: TextStyle(
                                  color: const Color(0xFF676D74),
                                  fontSize: 12,
                                  fontFamily: 'Poppins',
                                  fontWeight: FontWeight.w400,
                                  height: 1.33,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Opacity(
                        opacity: 0.60,
                        child: Expanded(
                          child: Column(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.start,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 6,
                            children: [
                              Container(width: 24, height: 24, child: Stack()),
                              Text(
                                'Account',
                                style: TextStyle(
                                  color: const Color(0xFF676D74),
                                  fontSize: 12,
                                  fontFamily: 'Poppins',
                                  fontWeight: FontWeight.w400,
                                  height: 1.33,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 911,
                child: Container(
                  width: 428,
                  height: 30,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.only(
                        bottomLeft: Radius.circular(20),
                        bottomRight: Radius.circular(20),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 264,
                top: 851,
                child: Container(
                  width: 61.46,
                  height: 4,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/61x4"),
                      fit: BoxFit.none,
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(2),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 139.37,
                top: 928,
                child: Container(
                  width: 148.15,
                  height: 5,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(100),
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
