import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(body: ListView(children: [LoginPengguna()])),
    );
  }
}

class LoginPengguna extends StatelessWidget {
  const LoginPengguna({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 428,
          height: 926,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: Colors.white,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
            shadows: [
              BoxShadow(
                color: Color(0x51000000),
                blurRadius: 24,
                offset: Offset(8, 12),
                spreadRadius: 0,
              ),
            ],
          ),
          child: Stack(
            children: [
              Positioned(
                left: -3,
                top: 0,
                child: Container(
                  width: 429,
                  height: 44,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: -3,
                top: 0,
                child: Container(
                  width: 429,
                  height: 44,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 111,
                top: 559,
                child: Container(
                  width: 218,
                  height: 55,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF4285F4),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x28000000),
                        blurRadius: 8,
                        offset: Offset(4, 4),
                        spreadRadius: 0,
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 175,
                top: 568,
                child: SizedBox(
                  width: 128,
                  height: 27,
                  child: Text(
                    'Masuk',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 24,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      letterSpacing: 1.92,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 146,
                top: 231,
                child: SizedBox(
                  width: 208,
                  height: 54,
                  child: Text(
                    'Masuk',
                    style: TextStyle(
                      color: Colors.black.withValues(alpha: 229),
                      fontSize: 38,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      letterSpacing: 3.04,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 79,
                top: 360,
                child: Container(
                  width: 279,
                  height: 43,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFF4285F4),
                      ),
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 84.17,
                top: 335,
                child: SizedBox(
                  width: 165.33,
                  height: 23,
                  child: Text(
                    'Masukan Email',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 14,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 92,
                top: 373,
                child: SizedBox(
                  width: 165.33,
                  height: 23,
                  child: Text(
                    'Email',
                    style: TextStyle(
                      color: const Color(0xFF726969),
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                      letterSpacing: 0.60,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 92,
                top: 373,
                child: SizedBox(
                  width: 165.33,
                  height: 23,
                  child: Text(
                    'Email',
                    style: TextStyle(
                      color: const Color(0xFF726969),
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                      letterSpacing: 0.60,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 79,
                top: 468,
                child: Container(
                  width: 277,
                  height: 44,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFF4285F4),
                      ),
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 84,
                top: 444,
                child: SizedBox(
                  width: 160,
                  height: 23,
                  child: Text(
                    'Masukan Password\n',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 14,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 88,
                top: 525,
                child: SizedBox(
                  width: 130,
                  height: 34,
                  child: Text(
                    'Daftar',
                    style: TextStyle(
                      color: const Color(0xFF4285F4),
                      fontSize: 13,
                      fontFamily: 'Roboto',
                      fontWeight: FontWeight.w400,
                      letterSpacing: 0.52,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 251,
                top: 525,
                child: SizedBox(
                  width: 116,
                  height: 17,
                  child: Text(
                    'Lupa password ?',
                    style: TextStyle(
                      color: const Color(0xFF4285F4),
                      fontSize: 13,
                      fontFamily: 'Roboto',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 92,
                top: 482,
                child: Text(
                  'Password',
                  style: TextStyle(
                    color: const Color(0xFF726969),
                    fontSize: 12,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                    letterSpacing: 0.60,
                  ),
                ),
              ),
              Positioned(
                left: 111,
                top: 559,
                child: Container(
                  width: 218,
                  height: 55,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF4285F4),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x28000000),
                        blurRadius: 8,
                        offset: Offset(4, 4),
                        spreadRadius: 0,
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 175,
                top: 568,
                child: SizedBox(
                  width: 128,
                  height: 27,
                  child: Text(
                    'Masuk',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 24,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      letterSpacing: 1.92,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 146,
                top: 231,
                child: SizedBox(
                  width: 208,
                  height: 54,
                  child: Text(
                    'Masuk',
                    style: TextStyle(
                      color: Colors.black.withValues(alpha: 229),
                      fontSize: 38,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      letterSpacing: 3.04,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 79,
                top: 360,
                child: Container(
                  width: 279,
                  height: 43,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFF4285F4),
                      ),
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 84.17,
                top: 335,
                child: SizedBox(
                  width: 165.33,
                  height: 23,
                  child: Text(
                    'Masukan Email',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 14,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 92,
                top: 373,
                child: SizedBox(
                  width: 165.33,
                  height: 23,
                  child: Text(
                    'Email',
                    style: TextStyle(
                      color: const Color(0xFF726969),
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                      letterSpacing: 0.60,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 92,
                top: 373,
                child: SizedBox(
                  width: 165.33,
                  height: 23,
                  child: Text(
                    'Email',
                    style: TextStyle(
                      color: const Color(0xFF726969),
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                      letterSpacing: 0.60,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 79,
                top: 468,
                child: Container(
                  width: 277,
                  height: 44,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFF4285F4),
                      ),
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 84,
                top: 444,
                child: SizedBox(
                  width: 160,
                  height: 23,
                  child: Text(
                    'Masukan Password\n',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 14,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 251,
                top: 525,
                child: SizedBox(
                  width: 116,
                  height: 17,
                  child: Text(
                    'Lupa password ?',
                    style: TextStyle(
                      color: const Color(0xFF4285F4),
                      fontSize: 13,
                      fontFamily: 'Roboto',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 92,
                top: 482,
                child: Text(
                  'Password',
                  style: TextStyle(
                    color: const Color(0xFF726969),
                    fontSize: 12,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                    letterSpacing: 0.60,
                  ),
                ),
              ),
              Positioned(
                left: 48,
                top: 655,
                child: Container(
                  width: 342,
                  height: 48,
                  decoration: BoxDecoration(color: Colors.white),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 342,
                          height: 48,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 1,
                                color: const Color(0xFF4280EF),
                              ),
                              borderRadius: BorderRadius.circular(8),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 82,
                        top: 12,
                        child: Container(
                          width: 24,
                          height: 24,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(),
                        ),
                      ),
                      Positioned(
                        left: 115,
                        top: 13,
                        child: SizedBox(
                          width: 174,
                          height: 17,
                          child: Text(
                            'Sign in with Google\n',
                            style: TextStyle(
                              color: const Color(0xFF4280EF),
                              fontSize: 16,
                              fontFamily: 'Plus Jakarta Sans',
                              fontWeight: FontWeight.w600,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 45,
                top: 720,
                child: Container(
                  width: 342,
                  height: 48,
                  decoration: BoxDecoration(color: Colors.white),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 342,
                          height: 48,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 1,
                                color: const Color(0xFF4280EF),
                              ),
                              borderRadius: BorderRadius.circular(8),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 82,
                        top: 12,
                        child: Container(
                          width: 24,
                          height: 24,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(),
                        ),
                      ),
                      Positioned(
                        left: 115,
                        top: 13,
                        child: SizedBox(
                          width: 174,
                          height: 17,
                          child: Text(
                            'Sign in with Facebook\n',
                            style: TextStyle(
                              color: const Color(0xFF4280EF),
                              fontSize: 16,
                              fontFamily: 'Plus Jakarta Sans',
                              fontWeight: FontWeight.w600,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 131,
                top: 736,
                child: Container(
                  width: 16,
                  height: 16,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 242,
                top: 517,
                child: Text(
                  'or ',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 16,
                    fontFamily: 'Plus Jakarta Sans',
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              Positioned(
                left: 24,
                top: 799,
                child: SizedBox(
                  width: 387,
                  height: 23,
                  child: Text(
                    'Dengan mendaftar, saya menyatakan telah membaca dan menyetujui Ketentuan Layanan & Kebijakan Tolongin',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 14,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
