import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(body: ListView(children: [Password()])),
    );
  }
}

class Password extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 428,
          height: 926,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: Colors.white,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
            shadows: [
              BoxShadow(
                color: Color(0x51000000),
                blurRadius: 24,
                offset: Offset(8, 12),
                spreadRadius: 0,
              ),
            ],
          ),
          child: Stack(
            children: [
              Positioned(
                left: 91,
                top: 682,
                child: Container(
                  width: 218,
                  height: 55,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF4285F4),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x28000000),
                        blurRadius: 8,
                        offset: Offset(4, 4),
                        spreadRadius: 0,
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 167,
                top: 691,
                child: SizedBox(
                  width: 128,
                  height: 27,
                  child: Text(
                    'Kirim',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 24,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      letterSpacing: 1.92,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 64,
                top: 240,
                child: SizedBox(
                  width: 343,
                  height: 54,
                  child: Text.rich(
                    TextSpan(
                      children: [
                        TextSpan(
                          text: 'Lupa Passwor',
                          style: TextStyle(
                            color: Colors.black.withValues(alpha: 229),
                            fontSize: 32,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w600,
                            letterSpacing: 2.56,
                          ),
                        ),
                        TextSpan(
                          text: 'd',
                          style: TextStyle(
                            color: Colors.black.withValues(alpha: 229),
                            fontSize: 32,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w600,
                            letterSpacing: 0.96,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 63,
                top: 474,
                child: Container(
                  width: 279,
                  height: 43,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFF4285F4),
                      ),
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 68.17,
                top: 449,
                child: SizedBox(
                  width: 165.33,
                  height: 23,
                  child: Text(
                    'Masukan Email',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 14,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 69,
                top: 339,
                child: SizedBox(
                  width: 175.33,
                  height: 23,
                  child: Text(
                    'Pesan',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 14,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 69,
                top: 362,
                child: SizedBox(
                  width: 275,
                  height: 23,
                  child: Text(
                    'Masukan email Anda dan tunggu kode etik akan dikirimkan.',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 13,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 76,
                top: 487,
                child: SizedBox(
                  width: 165.33,
                  height: 23,
                  child: Text(
                    'Email',
                    style: TextStyle(
                      color: const Color(0xFF726969),
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                      letterSpacing: 0.60,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 76,
                top: 487,
                child: SizedBox(
                  width: 165.33,
                  height: 23,
                  child: Text(
                    'Email',
                    style: TextStyle(
                      color: const Color(0xFF726969),
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                      letterSpacing: 0.60,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: -3,
                top: 0,
                child: Container(
                  width: 429,
                  height: 44,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
