import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(body: ListView(children: [Rating()])),
    );
  }
}

class Rating extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 428,
          height: 926,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  decoration: BoxDecoration(color: Colors.white),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 8,
                    children: [
                      Container(
                        width: 428,
                        height: 59,
                        padding: const EdgeInsets.symmetric(
                          horizontal: 20,
                          vertical: 12,
                        ),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          spacing: 155,
                          children: [
                            Container(
                              width: 82,
                              height: double.infinity,
                              child: Column(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.center,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                spacing: 10,
                                children: [
                                  Container(
                                    width: 376,
                                    height: 50,
                                    decoration: BoxDecoration(
                                      color: Colors.white,
                                    ),
                                  ),
                                  Container(
                                    width: 35,
                                    height: 27,
                                    decoration: BoxDecoration(
                                      color: Colors.black,
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            Container(
                              width: 102,
                              height: double.infinity,
                              padding: const EdgeInsets.only(right: 3),
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.center,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                spacing: 10,
                                children: [
                                  Container(
                                    width: 76,
                                    height: 14,
                                    clipBehavior: Clip.antiAlias,
                                    decoration: BoxDecoration(),
                                    child: Stack(),
                                  ),
                                  Container(
                                    width: 376,
                                    height: 50,
                                    decoration: BoxDecoration(
                                      color: Colors.white,
                                    ),
                                  ),
                                  Container(
                                    width: 79,
                                    height: 27,
                                    decoration: BoxDecoration(
                                      color: Colors.black,
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                      Container(
                        width: 388,
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          spacing: 192,
                          children: [
                            Container(
                              transform:
                                  Matrix4.identity()
                                    ..translate(0.0, 0.0)
                                    ..rotateZ(3.14),
                              width: 24,
                              height: 24,
                              clipBehavior: Clip.antiAlias,
                              decoration: BoxDecoration(),
                              child: Stack(),
                            ),
                            Text(
                              'Job Request',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                color: const Color(0xFF676D74),
                                fontSize: 24.55,
                                fontFamily: 'Hind',
                                fontWeight: FontWeight.w600,
                                height: 1.20,
                              ),
                            ),
                            Row(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.center,
                              spacing: 4,
                              children: [
                                Container(
                                  padding: const EdgeInsets.all(11),
                                  child: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment:
                                        CrossAxisAlignment.start,
                                    spacing: 10,
                                    children: [
                                      Container(
                                        width: 30,
                                        height: 30,
                                        child: Stack(),
                                      ),
                                    ],
                                  ),
                                ),
                                Container(
                                  padding: const EdgeInsets.all(11),
                                  child: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment:
                                        CrossAxisAlignment.start,
                                    spacing: 10,
                                    children: [
                                      Container(
                                        width: 30,
                                        height: 30,
                                        child: Stack(),
                                      ),
                                      Container(
                                        width: 12,
                                        height: 12,
                                        decoration: ShapeDecoration(
                                          color: Colors.white,
                                          shape: OvalBorder(),
                                        ),
                                      ),
                                      Container(
                                        transform:
                                            Matrix4.identity()
                                              ..translate(0.0, 0.0)
                                              ..rotateZ(-1.57),
                                        height: 12,
                                        decoration: ShapeDecoration(
                                          gradient: LinearGradient(
                                            begin: Alignment(0.26, 0.29),
                                            end: Alignment(1.07, 1.07),
                                            colors: [
                                              const Color(0xFF091114),
                                              const Color(0xC5404379),
                                              const Color(0xBF9670F6),
                                              const Color(0xBF91B2D4),
                                              const Color(0xFFDEF984),
                                            ],
                                          ),
                                          shape: OvalBorder(),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ],
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 163,
                child: Text(
                  'Your Request',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 16,
                    fontFamily: 'Hind',
                    fontWeight: FontWeight.w400,
                    height: 1,
                  ),
                ),
              ),
              Positioned(
                left: 96,
                top: 228,
                child: Container(
                  width: 33,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: const Color(0xFF999999),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 199,
                top: 228,
                child: Container(
                  width: 33,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: const Color(0xFF999999),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 302,
                top: 228,
                child: Container(
                  width: 33,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: const Color(0xFF999999),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 45,
                top: 210,
                child: Container(
                  width: 34,
                  height: 34,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 37,
                top: 245,
                child: Text(
                  'Requesting',
                  style: TextStyle(
                    color: const Color(0xFFD0D2D6),
                    fontSize: 10,
                    fontFamily: 'Hind',
                    fontWeight: FontWeight.w400,
                    height: 1.60,
                  ),
                ),
              ),
              Positioned(
                left: 147,
                top: 210,
                child: Container(
                  width: 34,
                  height: 34,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 126,
                top: 245,
                child: SizedBox(
                  width: 76,
                  child: Text(
                    'Job Comfirmation',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFFD0D2D6),
                      fontSize: 10,
                      fontFamily: 'Hind',
                      fontWeight: FontWeight.w400,
                      height: 1.60,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 250,
                top: 210,
                child: Container(
                  width: 34,
                  height: 34,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 229,
                top: 245,
                child: SizedBox(
                  width: 76,
                  child: Text(
                    'Working On',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFFD0D2D6),
                      fontSize: 10,
                      fontFamily: 'Hind',
                      fontWeight: FontWeight.w400,
                      height: 1.60,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 353,
                top: 210,
                child: Container(
                  width: 34,
                  height: 34,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 332,
                top: 245,
                child: SizedBox(
                  width: 76,
                  child: Text(
                    'Rating',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFF8A82FD),
                      fontSize: 10,
                      fontFamily: 'Hind',
                      fontWeight: FontWeight.w400,
                      height: 1.60,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 320,
                top: 382,
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.center,
                  crossAxisAlignment: CrossAxisAlignment.end,
                  spacing: 6,
                  children: [
                    Text(
                      '\$399',
                      style: TextStyle(
                        color: const Color(0xFF333333),
                        fontSize: 22,
                        fontFamily: 'Hind',
                        fontWeight: FontWeight.w600,
                        height: 1.14,
                      ),
                    ),
                    Text(
                      '\$599',
                      style: TextStyle(
                        color: const Color(0xFF6B6B6B),
                        fontSize: 14,
                        fontFamily: 'Hind',
                        fontWeight: FontWeight.w400,
                        textDecoration: TextDecoration.lineThrough,
                      ),
                    ),
                  ],
                ),
              ),
              Positioned(
                left: 166,
                top: 326,
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  spacing: 10,
                  children: [
                    Text(
                      'Nail Art',
                      style: TextStyle(
                        color: const Color(0xFF333333),
                        fontSize: 24.55,
                        fontFamily: 'Hind',
                        fontWeight: FontWeight.w600,
                        height: 1.02,
                      ),
                    ),
                  ],
                ),
              ),
              Positioned(
                left: 166,
                top: 351,
                child: Text(
                  'French Tips',
                  style: TextStyle(
                    color: const Color(0xFF676D74),
                    fontSize: 15.41,
                    fontFamily: 'Hind',
                    fontWeight: FontWeight.w400,
                    height: 1.62,
                  ),
                ),
              ),
              Positioned(
                left: 166,
                top: 379,
                child: Text(
                  'Total',
                  style: TextStyle(
                    color: const Color(0xFF676D74),
                    fontSize: 15.41,
                    fontFamily: 'Hind',
                    fontWeight: FontWeight.w400,
                    height: 1.62,
                  ),
                ),
              ),
              Positioned(
                left: 378,
                top: 351,
                child: Text(
                  'x 1',
                  style: TextStyle(
                    color: const Color(0xFF676D74),
                    fontSize: 15.41,
                    fontFamily: 'Hind',
                    fontWeight: FontWeight.w400,
                    height: 1.62,
                  ),
                ),
              ),
              Positioned(
                left: 27,
                top: 432,
                child: Text(
                  'Booking',
                  style: TextStyle(
                    color: const Color(0xFF333333),
                    fontSize: 24.55,
                    fontFamily: 'Hind',
                    fontWeight: FontWeight.w600,
                    height: 1.02,
                  ),
                ),
              ),
              Positioned(
                left: 44,
                top: 485,
                child: Text(
                  'Name',
                  style: TextStyle(
                    color: const Color(0xFF676D74),
                    fontSize: 15.41,
                    fontFamily: 'Hind',
                    fontWeight: FontWeight.w400,
                    height: 1.62,
                  ),
                ),
              ),
              Positioned(
                left: 44,
                top: 514,
                child: Text(
                  'Date',
                  style: TextStyle(
                    color: const Color(0xFF676D74),
                    fontSize: 15.41,
                    fontFamily: 'Hind',
                    fontWeight: FontWeight.w400,
                    height: 1.62,
                  ),
                ),
              ),
              Positioned(
                left: 44,
                top: 543,
                child: Text(
                  'Time',
                  style: TextStyle(
                    color: const Color(0xFF676D74),
                    fontSize: 15.41,
                    fontFamily: 'Hind',
                    fontWeight: FontWeight.w400,
                    height: 1.62,
                  ),
                ),
              ),
              Positioned(
                left: 44,
                top: 571,
                child: Text(
                  'Notes',
                  style: TextStyle(
                    color: const Color(0xFF676D74),
                    fontSize: 15.41,
                    fontFamily: 'Hind',
                    fontWeight: FontWeight.w400,
                    height: 1.62,
                  ),
                ),
              ),
              Positioned(
                left: 127,
                top: 485,
                child: Text(
                  ': Jane Doe',
                  style: TextStyle(
                    color: const Color(0xFF676D74),
                    fontSize: 15.41,
                    fontFamily: 'Hind',
                    fontWeight: FontWeight.w400,
                    height: 1.62,
                  ),
                ),
              ),
              Positioned(
                left: 127,
                top: 514,
                child: Text(
                  ': 21',
                  style: TextStyle(
                    color: const Color(0xFF676D74),
                    fontSize: 15.41,
                    fontFamily: 'Hind',
                    fontWeight: FontWeight.w400,
                    height: 1.62,
                  ),
                ),
              ),
              Positioned(
                left: 157,
                top: 514,
                child: Text(
                  'January',
                  style: TextStyle(
                    color: const Color(0xFF676D74),
                    fontSize: 15.41,
                    fontFamily: 'Hind',
                    fontWeight: FontWeight.w400,
                    height: 1.62,
                  ),
                ),
              ),
              Positioned(
                left: 220,
                top: 514,
                child: Text(
                  '2025',
                  style: TextStyle(
                    color: const Color(0xFF676D74),
                    fontSize: 15.41,
                    fontFamily: 'Hind',
                    fontWeight: FontWeight.w400,
                    height: 1.62,
                  ),
                ),
              ),
              Positioned(
                left: 127,
                top: 543,
                child: Text(
                  ': 16 . 30',
                  style: TextStyle(
                    color: const Color(0xFF676D74),
                    fontSize: 15.41,
                    fontFamily: 'Hind',
                    fontWeight: FontWeight.w400,
                    height: 1.62,
                  ),
                ),
              ),
              Positioned(
                left: 127,
                top: 572,
                child: Text(
                  ': Please bring a glitter',
                  style: TextStyle(
                    color: const Color(0xFF676D74),
                    fontSize: 15.41,
                    fontFamily: 'Hind',
                    fontWeight: FontWeight.w400,
                    height: 1.62,
                  ),
                ),
              ),
              Positioned(
                left: 44,
                top: 623,
                child: Container(
                  width: 64,
                  height: 64,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 113,
                top: 623,
                child: Container(
                  width: 64,
                  height: 64,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 182,
                top: 623,
                child: Container(
                  width: 64,
                  height: 64,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 251,
                top: 623,
                child: Container(
                  width: 64,
                  height: 64,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 320,
                top: 622,
                child: Container(
                  width: 64,
                  height: 64,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 29,
                top: 697,
                child: Text(
                  'Review your Request',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 13,
                    fontFamily: 'Hind',
                    fontWeight: FontWeight.w400,
                    height: 1.92,
                  ),
                ),
              ),
              Positioned(
                left: 27,
                top: 725,
                child: Container(
                  width: 373,
                  height: 99,
                  decoration: BoxDecoration(color: const Color(0xFFF3F3F3)),
                ),
              ),
              Positioned(
                left: 0,
                top: 852,
                child: Container(
                  width: 428,
                  padding: const EdgeInsets.only(top: 12, left: 12, right: 12),
                  decoration: BoxDecoration(color: Colors.white),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Expanded(
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          spacing: 6,
                          children: [
                            Container(
                              width: 24,
                              height: 24,
                              child: Stack(
                                children: [
                                  Positioned(
                                    left: -24.90,
                                    top: 0,
                                    child: Container(
                                      width: 73.80,
                                      height: 24,
                                      child: Column(
                                        mainAxisSize: MainAxisSize.min,
                                        mainAxisAlignment:
                                            MainAxisAlignment.start,
                                        crossAxisAlignment:
                                            CrossAxisAlignment.center,
                                        spacing: 6,
                                        children: [
                                          Container(
                                            width: 24,
                                            height: 24,
                                            clipBehavior: Clip.antiAlias,
                                            decoration: BoxDecoration(),
                                            child: Stack(),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            Text(
                              'Home',
                              style: TextStyle(
                                fontSize: 12,
                                fontFamily: 'Hind',
                                fontWeight: FontWeight.w500,
                                height: 1.33,
                              ),
                            ),
                          ],
                        ),
                      ),
                      Opacity(
                        opacity: 0.60,
                        child: Expanded(
                          child: Column(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.start,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 7,
                            children: [
                              Container(width: 24, height: 24, child: Stack()),
                              Text(
                                'Explore',
                                style: TextStyle(
                                  color: const Color(0xFF676D74),
                                  fontSize: 12,
                                  fontFamily: 'Poppins',
                                  fontWeight: FontWeight.w400,
                                  height: 1.33,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Opacity(
                        opacity: 0.60,
                        child: Expanded(
                          child: Column(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.start,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 6,
                            children: [
                              Container(width: 24, height: 24, child: Stack()),
                              Opacity(
                                opacity: 0.90,
                                child: Text(
                                  'Chat',
                                  style: TextStyle(
                                    color: const Color(0xFF676D74),
                                    fontSize: 12,
                                    fontFamily: 'Poppins',
                                    fontWeight: FontWeight.w500,
                                    height: 1.33,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Opacity(
                        opacity: 0.60,
                        child: Expanded(
                          child: Column(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.start,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 6,
                            children: [
                              Container(width: 24, height: 24, child: Stack()),
                              Text(
                                'Blog',
                                style: TextStyle(
                                  color: const Color(0xFF676D74),
                                  fontSize: 12,
                                  fontFamily: 'Poppins',
                                  fontWeight: FontWeight.w400,
                                  height: 1.33,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Opacity(
                        opacity: 0.60,
                        child: Expanded(
                          child: Column(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.start,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 6,
                            children: [
                              Container(width: 24, height: 24, child: Stack()),
                              Text(
                                'Account',
                                style: TextStyle(
                                  color: const Color(0xFF676D74),
                                  fontSize: 12,
                                  fontFamily: 'Poppins',
                                  fontWeight: FontWeight.w400,
                                  height: 1.33,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 911,
                child: Container(
                  width: 428,
                  height: 30,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.only(
                        bottomLeft: Radius.circular(20),
                        bottomRight: Radius.circular(20),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 264,
                top: 851,
                child: Container(
                  width: 61.46,
                  height: 4,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/61x4"),
                      fit: BoxFit.none,
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(2),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 139.37,
                top: 928,
                child: Container(
                  width: 148.15,
                  height: 5,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(100),
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
