import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(body: ListView(children: [RegistrationPekerja()])),
    );
  }
}

class RegistrationPekerja extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 428,
          height: 926,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: Colors.white,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
            shadows: [
              BoxShadow(
                color: Color(0x51000000),
                blurRadius: 24,
                offset: Offset(8, 12),
                spreadRadius: 0,
              ),
            ],
          ),
          child: Stack(
            children: [
              Positioned(
                left: 101,
                top: 637,
                child: Container(
                  width: 218,
                  height: 55,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF4285F4),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x28000000),
                        blurRadius: 8,
                        offset: Offset(4, 4),
                        spreadRadius: 0,
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 127,
                top: 647,
                child: SizedBox(
                  width: 166,
                  height: 27,
                  child: Text(
                    'Selanjutnya',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 24,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      letterSpacing: 1.92,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 136,
                top: 191,
                child: SizedBox(
                  width: 142,
                  height: 54,
                  child: Text(
                    'Daftar',
                    style: TextStyle(
                      color: Colors.black.withValues(alpha: 229),
                      fontSize: 38,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      letterSpacing: 3.04,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 74,
                top: 391,
                child: Container(
                  width: 275,
                  height: 43,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFF4285F4),
                      ),
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 79.09,
                top: 366,
                child: SizedBox(
                  width: 162.96,
                  height: 23,
                  child: Text(
                    'Nomer Telepon',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 14,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 86.81,
                top: 404,
                child: SizedBox(
                  width: 162.96,
                  height: 23,
                  child: Text(
                    'Email',
                    style: TextStyle(
                      color: const Color(0xFF726969),
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                      letterSpacing: 0.60,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 72,
                top: 315,
                child: Container(
                  width: 275,
                  height: 43,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFF4285F4),
                      ),
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 77.09,
                top: 290,
                child: SizedBox(
                  width: 162.96,
                  height: 23,
                  child: Text(
                    'Nama',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 14,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 84.81,
                top: 328,
                child: SizedBox(
                  width: 162.96,
                  height: 23,
                  child: Text(
                    'Nama',
                    style: TextStyle(
                      color: const Color(0xFF726969),
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                      letterSpacing: 0.60,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 72,
                top: 475,
                child: Container(
                  width: 277,
                  height: 44,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFF4285F4),
                      ),
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 77,
                top: 451,
                child: SizedBox(
                  width: 160,
                  height: 23,
                  child: Text(
                    'Masukan Email\n',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 14,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 110,
                top: 700,
                child: SizedBox(
                  width: 130,
                  height: 34,
                  child: Text(
                    'Sudah memiliki akun ?',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 13,
                      fontFamily: 'Roboto',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 259,
                top: 700,
                child: SizedBox(
                  width: 130,
                  height: 34,
                  child: Text(
                    'Masuk',
                    style: TextStyle(
                      color: const Color(0xFF4285F4),
                      fontSize: 13,
                      fontFamily: 'Roboto',
                      fontWeight: FontWeight.w400,
                      letterSpacing: 0.52,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 85,
                top: 489,
                child: Text(
                  'Email',
                  style: TextStyle(
                    color: const Color(0xFF726969),
                    fontSize: 12,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                    letterSpacing: 0.60,
                  ),
                ),
              ),
              Positioned(
                left: 72,
                top: 560,
                child: Container(
                  width: 277,
                  height: 44,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFF4285F4),
                      ),
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 77,
                top: 536,
                child: SizedBox(
                  width: 201,
                  height: 23,
                  child: Text(
                    'Masukan Password\n',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 14,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 85,
                top: 574,
                child: Text(
                  'Password',
                  style: TextStyle(
                    color: const Color(0xFF726969),
                    fontSize: 12,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                    letterSpacing: 0.60,
                  ),
                ),
              ),
              Positioned(
                left: -3,
                top: 0,
                child: Container(
                  width: 429,
                  height: 44,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
