import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(body: ListView(children: [TerimaPekerjaan()])),
    );
  }
}

class TerimaPekerjaan extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 428,
          height: 926,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 50,
                top: 560,
                child: Container(
                  width: 348,
                  height: 103,
                  decoration: BoxDecoration(color: const Color(0xFFEEEEEE)),
                ),
              ),
              Positioned(
                left: 3,
                top: 93,
                child: Container(
                  width: 413,
                  height: 304,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/413x304"),
                      fit: BoxFit.cover,
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 6,
                top: 423,
                child: Container(
                  width: 264,
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 4,
                    children: [
                      Container(
                        width: 175,
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          spacing: 10,
                          children: [
                            Container(
                              width: double.infinity,
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.start,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                spacing: 10,
                                children: [
                                  Text(
                                    'Angkat Barang ',
                                    style: TextStyle(
                                      color: const Color(0xFF333333),
                                      fontSize: 24.55,
                                      fontFamily: 'Hind',
                                      fontWeight: FontWeight.w600,
                                      height: 1.02,
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 7,
                top: 456,
                child: Container(
                  width: 264,
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 4,
                    children: [
                      Container(
                        width: 175,
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          spacing: 10,
                          children: [
                            Container(
                              width: double.infinity,
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.start,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                spacing: 10,
                                children: [
                                  Text(
                                    'Rp. 150.000',
                                    style: TextStyle(
                                      color: const Color(0xFF59E359),
                                      fontSize: 24.55,
                                      fontFamily: 'Hind',
                                      fontWeight: FontWeight.w600,
                                      height: 1.02,
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 52,
                top: 489,
                child: SizedBox(
                  width: 343,
                  child: Text(
                    'bantu angkut barang kotakan isi makanan ringan di transmart rungkut surabaya, dibutuhkan 10 orang ',
                    style: TextStyle(
                      color: const Color(0xFF333333),
                      fontSize: 12,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                      height: 1.50,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 54,
                top: 698,
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  spacing: 12,
                  children: [
                    Container(
                      width: 27.27,
                      height: 27.27,
                      decoration: ShapeDecoration(
                        image: DecorationImage(
                          image: NetworkImage("https://placehold.co/27x27"),
                          fit: BoxFit.cover,
                        ),
                        shape: OvalBorder(),
                      ),
                    ),
                    Container(
                      width: 30,
                      height: 30,
                      decoration: ShapeDecoration(
                        shape: OvalBorder(side: BorderSide(width: 1)),
                      ),
                    ),
                    Row(
                      mainAxisSize: MainAxisSize.min,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      spacing: 10,
                      children: [
                        Text(
                          'Reggin A.',
                          style: TextStyle(
                            color: const Color(0xFF1D1F24),
                            fontSize: 14,
                            fontFamily: 'Hind',
                            fontWeight: FontWeight.w500,
                            height: 1.43,
                          ),
                        ),
                        Text(
                          '@REGGINA',
                          style: TextStyle(
                            color: const Color(0xFF827BEB),
                            fontSize: 14,
                            fontFamily: 'Hind',
                            fontWeight: FontWeight.w600,
                            height: 1.29,
                          ),
                        ),
                      ],
                    ),
                  ],
                ),
              ),
              Positioned(
                left: 355,
                top: 416,
                child: Container(
                  width: 36,
                  height: 36,
                  padding: const EdgeInsets.symmetric(
                    horizontal: 6,
                    vertical: 2,
                  ),
                  decoration: ShapeDecoration(
                    color: const Color(0x4C2B2B2B),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 4,
                    children: [
                      Container(width: 22, height: 22, child: Stack()),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 47,
                top: 56,
                child: Container(
                  transform:
                      Matrix4.identity()
                        ..translate(0.0, 0.0)
                        ..rotateZ(3.14),
                  width: 24,
                  height: 24,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 52,
                top: 686,
                child: Container(
                  width: 332.01,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: const Color(0xD6676D74),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 59,
                top: 580,
                child: Text(
                  'Date  ',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 14,
                    fontFamily: 'Rubik',
                    fontWeight: FontWeight.w400,
                    height: 1.14,
                  ),
                ),
              ),
              Positioned(
                left: 104,
                top: 580,
                child: Text(
                  ': 21 - 05 - 2025',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 14,
                    fontFamily: 'Rubik',
                    fontWeight: FontWeight.w400,
                    height: 1.14,
                  ),
                ),
              ),
              Positioned(
                left: 104,
                top: 604,
                child: Text(
                  ': 19.20 - 20.35',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 14,
                    fontFamily: 'Rubik',
                    fontWeight: FontWeight.w400,
                    height: 1.14,
                  ),
                ),
              ),
              Positioned(
                left: 104,
                top: 628,
                child: Text(
                  ': Tambah Konsumsi',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 14,
                    fontFamily: 'Rubik',
                    fontWeight: FontWeight.w400,
                    height: 1.14,
                  ),
                ),
              ),
              Positioned(
                left: 59,
                top: 604,
                child: Text(
                  'Time ',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 14,
                    fontFamily: 'Rubik',
                    fontWeight: FontWeight.w400,
                    height: 1.14,
                  ),
                ),
              ),
              Positioned(
                left: 59,
                top: 628,
                child: Text(
                  'Notes',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 14,
                    fontFamily: 'Rubik',
                    fontWeight: FontWeight.w400,
                    height: 1.14,
                  ),
                ),
              ),
              Positioned(
                left: 40,
                top: 767,
                child: Container(
                  width: 178,
                  height: 208,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(color: const Color(0xFF676D74)),
                  child: Stack(
                    children: [
                      Positioned(
                        left: -43,
                        top: -52,
                        child: Container(
                          width: 229.70,
                          height: 344,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage(
                                "https://placehold.co/230x344",
                              ),
                              fit: BoxFit.cover,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 227,
                top: 767,
                child: Container(
                  width: 178,
                  height: 208,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(color: const Color(0xFF676D74)),
                  child: Stack(
                    children: [
                      Positioned(
                        left: -26,
                        top: -50,
                        child: Container(
                          width: 229.70,
                          height: 344,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage(
                                "https://placehold.co/230x344",
                              ),
                              fit: BoxFit.cover,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 831,
                child: Container(
                  width: 376,
                  height: 58,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 18,
                        top: 0,
                        child: Container(
                          height: 58,
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.start,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 13,
                            children: [
                              Container(
                                width: 30,
                                height: 30,
                                clipBehavior: Clip.antiAlias,
                                decoration: BoxDecoration(),
                                child: Stack(),
                              ),
                              Container(
                                width: 315,
                                height: 44,
                                padding: const EdgeInsets.all(10),
                                decoration: ShapeDecoration(
                                  color: const Color(0xFF827BEB),
                                  shape: RoundedRectangleBorder(
                                    borderRadius: BorderRadius.circular(23),
                                  ),
                                ),
                                child: Row(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.center,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  spacing: 10,
                                  children: [
                                    Text(
                                      'Apply Job',
                                      style: TextStyle(
                                        color: Colors.white,
                                        fontSize: 17.12,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w400,
                                        height: 1.05,
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
