import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(body: ListView(children: [VariantDetails()])),
    );
  }
}

class VariantDetails extends StatelessWidget {
  const VariantDetails({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 428,
          height: 425,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: Colors.white,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(24),
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: 43,
                top: 102,
                child: SizedBox(
                  width: 251,
                  height: 32,
                  child: Text(
                    'Title ',
                    style: TextStyle(
                      color: const Color(0xFF676D74),
                      fontSize: 12.36,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                      height: 2.59,
                      letterSpacing: -0.50,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 43,
                top: 167,
                child: Container(
                  width: 342,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: const Color(0xFFCBCBCB),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 43,
                top: 134,
                child: SizedBox(
                  width: 325,
                  height: 21,
                  child: Text(
                    'Paket 7 Bulan',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 20,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                      letterSpacing: -0.30,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 43,
                top: 191,
                child: SizedBox(
                  width: 251,
                  height: 32,
                  child: Text(
                    'Price',
                    style: TextStyle(
                      color: const Color(0xFF676D74),
                      fontSize: 12.36,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                      height: 2.59,
                      letterSpacing: -0.50,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 43,
                top: 256,
                child: Container(
                  width: 342,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: const Color(0xFFCBCBCB),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 43,
                top: 223,
                child: SizedBox(
                  width: 325,
                  height: 21,
                  child: Text(
                    'Rp. 1.300.000',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 20,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                      letterSpacing: -0.30,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 19,
                top: 66.50,
                child: Container(
                  width: 389,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: const Color(0xFFCBCBCB),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 34,
                top: 323,
                child: Container(
                  width: 360,
                  height: 60,
                  padding: const EdgeInsets.all(10),
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF4280EF),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(41),
                    ),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 10,
                    children: [
                      Text(
                        'Confirm',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 20,
                          fontFamily: 'Plus Jakarta Sans',
                          fontWeight: FontWeight.w600,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 146,
                top: 26,
                child: SizedBox(
                  width: 135.82,
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 8,
                    children: [
                      SizedBox(
                        width: 341,
                        child: Text(
                          'Variant Details',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: const Color(0xFF3B3936),
                            fontSize: 24,
                            fontFamily: 'Rubik',
                            fontWeight: FontWeight.w500,
                            height: 1.33,
                            letterSpacing: -0.50,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
