import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(body: ListView(children: [YourRequest()])),
    );
  }
}

class YourRequest extends StatelessWidget {
  const YourRequest({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 428,
          height: 926,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 17.30,
                child: SizedBox(
                  width: 428,
                  height: 48,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 389.33,
                        top: 17.33,
                        child: Opacity(
                          opacity: 0.35,
                          child: Container(
                            width: 22,
                            height: 11.33,
                            decoration: ShapeDecoration(
                              shape: RoundedRectangleBorder(
                                side: BorderSide(width: 1),
                                borderRadius: BorderRadius.circular(2.67),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 391.33,
                        top: 19.33,
                        child: Container(
                          width: 18,
                          height: 7.33,
                          decoration: ShapeDecoration(
                            color: Colors.black,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(1.33),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 21,
                        top: 7.33,
                        child: SizedBox(
                          width: 54,
                          height: 21,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 7,
                                child: SizedBox(
                                  width: 54,
                                  child: Text(
                                    '9:41',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 15,
                                      fontFamily: 'SF Pro Text',
                                      fontWeight: FontWeight.w600,
                                      letterSpacing: -0.30,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 151,
                top: 46.30,
                child: SizedBox(
                  width: 135,
                  height: 73,
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 8,
                    children: [
                      SizedBox(
                        width: 341,
                        child: Text(
                          'Your Request',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: const Color(0xFF3B3936),
                            fontSize: 24,
                            fontFamily: 'Rubik',
                            fontWeight: FontWeight.w500,
                            height: 1.33,
                            letterSpacing: -0.50,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 21,
                top: 69,
                child: Container(
                  height: 28,
                  padding: const EdgeInsets.all(10),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 10,
                    children: [
                      Container(
                        width: 24,
                        height: 24,
                        clipBehavior: Clip.antiAlias,
                        decoration: BoxDecoration(),
                        child: Stack(),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 151,
                child: Container(
                  width: 428,
                  height: 159,
                  decoration: BoxDecoration(color: Colors.white),
                ),
              ),
              Positioned(
                left: 174,
                top: 170,
                child: SizedBox(
                  width: 228.96,
                  child: Text(
                    'Di Cari! Kasir dan Pegawai Mini Market',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 15,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      height: 1.20,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 174,
                top: 222,
                child: SizedBox(
                  width: 239,
                  child: Text(
                    'Pria dan Wanita, Part-time, diutamakan yang memiliki pengalaman dalam menangani...',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 9.27,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w300,
                      height: 1.51,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 174,
                top: 250,
                child: SizedBox(
                  width: 76.11,
                  child: Text(
                    'see more',
                    style: TextStyle(
                      color: const Color(0xFF4285F4),
                      fontSize: 9.27,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w300,
                      height: 1.62,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 20,
                top: 160,
                child: Container(
                  width: 141,
                  height: 141,
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF676D74),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(9),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: -2,
                        top: -19,
                        child: Container(
                          width: 144,
                          height: 180,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage(
                                "https://placehold.co/144x180",
                              ),
                              fit: BoxFit.cover,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 364,
                top: 253,
                child: Container(
                  width: 45,
                  height: 45,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 25,
                top: 131,
                child: Text(
                  'Someone Apply to your Request',
                  style: TextStyle(
                    color: const Color(0xFF5BA092),
                    fontSize: 9.27,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                    height: 1.51,
                  ),
                ),
              ),
              Positioned(
                left: 25,
                top: 344,
                child: Text(
                  'See your Request',
                  style: TextStyle(
                    color: const Color(0xFF5BA092),
                    fontSize: 9.27,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                    height: 1.51,
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 518,
                child: SizedBox(
                  width: 428,
                  height: 155,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 428,
                          height: 155,
                          decoration: BoxDecoration(color: Colors.white),
                        ),
                      ),
                      Positioned(
                        left: 19,
                        top: 7,
                        child: Container(
                          width: 141,
                          height: 141,
                          clipBehavior: Clip.antiAlias,
                          decoration: ShapeDecoration(
                            color: const Color(0xFF676D74),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(9),
                            ),
                          ),
                          child: Stack(
                            children: [
                              Positioned(
                                left: -2,
                                top: -19,
                                child: SizedBox(width: 144, height: 180),
                              ),
                              Positioned(
                                left: -66,
                                top: -15,
                                child: Container(
                                  width: 228,
                                  height: 171,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage(
                                        "https://placehold.co/228x171",
                                      ),
                                      fit: BoxFit.cover,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 179,
                        top: 33,
                        child: SizedBox(
                          width: 233,
                          child: Text(
                            'Open Requitement Pegawai Laundry',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 15,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w600,
                              height: 1.20,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 179,
                        top: 75,
                        child: SizedBox(
                          width: 217,
                          child: Text(
                            'Open full time hingga part-time job buat para mahasiswa yang mau nambah uang jajan...',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 9.27,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w300,
                              height: 1.51,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 179,
                        top: 107,
                        child: Text(
                          'see more',
                          style: TextStyle(
                            color: const Color(0xFF4285F4),
                            fontSize: 9.27,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w300,
                            height: 1.62,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 359,
                child: Container(
                  width: 428,
                  height: 159,
                  decoration: BoxDecoration(color: Colors.white),
                ),
              ),
              Positioned(
                left: 176,
                top: 392,
                child: SizedBox(
                  width: 228.96,
                  child: Text(
                    'Angkat Barang ',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 15,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      height: 1.20,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 176,
                top: 416,
                child: SizedBox(
                  width: 239,
                  child: Text(
                    'bantu angkut barang kotakan isi makanan ringan di transmart rungkut surabaya, dibutuhkan 10 orang... ',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 9.27,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w300,
                      height: 1.51,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 176,
                top: 471,
                child: SizedBox(
                  width: 76.11,
                  child: Text(
                    'see more',
                    style: TextStyle(
                      color: const Color(0xFF4285F4),
                      fontSize: 9.27,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w300,
                      height: 1.62,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 20,
                top: 368,
                child: Container(
                  width: 141,
                  height: 141,
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF676D74),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(9),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 141,
                          height: 141,
                          decoration: ShapeDecoration(
                            image: DecorationImage(
                              image: NetworkImage(
                                "https://placehold.co/141x141",
                              ),
                              fit: BoxFit.cover,
                            ),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(8),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 674,
                child: SizedBox(
                  width: 428,
                  height: 155,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 428,
                          height: 155,
                          decoration: BoxDecoration(color: Colors.white),
                        ),
                      ),
                      Positioned(
                        left: 19,
                        top: 7,
                        child: Container(
                          width: 141,
                          height: 141,
                          clipBehavior: Clip.antiAlias,
                          decoration: ShapeDecoration(
                            color: const Color(0xFF676D74),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(9),
                            ),
                          ),
                          child: Stack(
                            children: [
                              Positioned(
                                left: -2,
                                top: -19,
                                child: SizedBox(width: 144, height: 180),
                              ),
                              Positioned(
                                left: -9,
                                top: -61,
                                child: Container(
                                  width: 157.33,
                                  height: 236,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage(
                                        "https://placehold.co/157x236",
                                      ),
                                      fit: BoxFit.cover,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 179,
                        top: 33,
                        child: SizedBox(
                          width: 233,
                          child: Text(
                            'Bantuin angkat-angkat pindahan',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 15,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w600,
                              height: 1.20,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 179,
                        top: 75,
                        child: SizedBox(
                          width: 217,
                          child: Text(
                            'Bantuin aku angakt-angkat habis pindahan dong, nanti ada tambahannya disana...',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 9.27,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w300,
                              height: 1.51,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 179,
                        top: 107,
                        child: Text(
                          'see more',
                          style: TextStyle(
                            color: const Color(0xFF4285F4),
                            fontSize: 9.27,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w300,
                            height: 1.62,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
